### ISSUE TITLE
Use tags to filter list vms

### ISSUE THREAD

**Issue by GrandeTartine** [vmware/vsphere-automation-sdk-python#101]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue)

Hello.

I was wondering, is there any way to list vms/datastores/others stuff with a filter on tags ?

I wish to do it like in PowerCli (for example: $VMs = Get-VM -Tag "PreProd") but I didn't see any information to do it with Python SDK.

I'm a beggenner so maybe I miss something. 

Best regards

**Comment by FumbleBe** [comment]
Good question ! I wish I can do it too, but can't find a way...

**Comment by tianhao64** [comment]
@GrandeTartine @FumbleBe Will this help?
https://vmware.github.io/vsphere-automation-sdk-python/vsphere/6.7.0/com.vmware.cis.html?highlight=tagging#com.vmware.cis.tagging_client.TagAssociation.list_attached_objects_on_tags

**Comment by GrandeTartine** [comment]
Hello.

Yes, this is what I need. Thanks.
Sorry that I completely missed that in the documentation.

**Comment by bpg168** [comment]
list_attached_objects_on_tags(tag_ids)
This method returns the list of attached object identifiers.
How do we find the names of VirtualMachines from object identifiers.
Please share the link to documentation or share an example.

**Comment by inflatador** [comment]
@tianhao64  or anyone else, see @bpg168  's statement above. Is there a way to resolve these DynamicIDs like "type='VirtualMachine', id='vm-901925'" back to virtual machine names?

**Comment by inflatador** [comment]
Just following up, someone far smarter than I pointed me in [the right direction](https://virtuallysober.com/2019/01/23/getting-vm-tags-across-vcenters-using-powershell-rest-apis/). Now we can resolve these back to machine names
First, get the list of resources associated with a particular tag
```	
mine_vms = {}
	for tag_id in tag_ids:
		tag_model = v_client.tagging.Tag.get(tag_id)
		if "mine" in tag_model.name:
			print("Tag ID '{}', name '{}', category '{}'".format(
					tag_model.id, tag_model.name, tag_model.category_id
			))
			mine_vms[tag_model.name] = v_client.tagging.TagAssociation.list_attached_objects(tag_model.id)

```

For simplicity's sake, I'm only going to show the list of resources associated with a single key in the "mine_vms" dict, let's call it "staging":
```
	desired_vms = mine_vms['staging']
	my_vms = []
	for vm in desired_vms:
			my_vms.append(vm.id)

	my_vms = set(my_vms)
	vm_scrape = v_client.vcenter.VM.list(VM.FilterSpec(vms=(my_vms)))
	print ("Found your VMs at {}".format(vm_scrape))
```

Apologies if this is sloppy or incoherent, the breakthru for me was the link above, and running  `dir(mine_vms['staging'][0])` which shows the methods. To resolve the DynamicID IDs to VMs, we have to use that ".id" method.
