### ISSUE TITLE
Try to add RDM disk to VM got error "Incompatible device backing specified for device '0'".

### ISSUE THREAD

**Issue by 14kosta** [vmware/vsphere-automation-sdk-python#119]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
 Answer: yes
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
I use Version 6.7.0.1150 Build 8170132
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)
Answer: yes

## Environment
- sdk package version: 

(vSphere_sdk_virt_env) [root@SIOVM-9 ~]# pip list | grep v
pyvmomi               6.7.1             
vapi-client-bindings  1.5.0             
vapi-common-client    2.10.2            
vapi-runtime          2.10.2            
vapi-vmc-client       2.10.2            
vmc-app-python-sdk    2.2.0.0.0.15184434
vmc-client-bindings   1.3.0             
(vSphere_sdk_virt_env) [root@SIOVM-9 ~]# 

- python version:

(vSphere_sdk_virt_env) [root@SIOVM-9 ~]# python --version
Python 3.5.1
(vSphere_sdk_virt_env) [root@SIOVM-9 ~]# 

- vSphere version:
Version 6.7.0.1150 Build 8170132

- Operating System/Shell (used to run SDK-based apps):
Red Hat 7.3
## Steps or code snippet to reproduce
I attached the sample code that i used. failed the function add_remove_vm_disk. Other functions succeeded.
[vsphere_api_1.zip](https://github.com/vmware/vsphere-automation-sdk-python/files/2620710/vsphere_api_1.zip)

Problem description:
Hi,

Trying to add device /vmfs/devices/disks/eui.57df0280647efa2de9751c5d0000000a as RDM disk to VM I do the following 
1. Create meta and flat vdmk files in the datastore_path:
 datastore_root_path = "[vm1_thick] RHEL70_thick13"
 datastore_path = datastore_root_path + '/RHEL70_thick13_2.vmdk'
 
 by running
    vdm = service_instance.content.virtualDiskManager
    task = vdm.CreateVirtualDisk(
        datastore_path, datacenter_mo,
        vim.VirtualDiskManager.DeviceBackedVirtualDiskSpec(
            diskType='rdmp', adapterType='lsiLogic',
            device = "/vmfs/devices/disks/eui.57df0280647efa2de9751c5d0000000a"))
    pyVim.task.WaitForTask(task)

 After this call in the directory
 /vmfs/volumes/vm1_thick/RHEL70_thick13 appear meta file RHEL70_thick13_2.vmdk and disk file RHEL70_thick13_2-rdmp.vmdk

2. Run the following code adapted from https://github.com/vmware/vsphere-automation-sdk-python/tree/master/samples/vsphere/vcenter/vm/hardware/disk.py

        disk_create_spec = Disk.CreateSpec(
            type=Disk.HostBusAdapterType.SCSI,
            backing=Disk.BackingSpec(type=Disk.BackingType.VMDK_FILE,
                                     vmdk_file=datastore_path))
        disk = self.client.vcenter.vm.hardware.Disk.create(vm=self.vm, spec=disk_create_spec)
3. Got the following error:
  File "/root/vmware/vsphere_api.py", line 320, in add_remove_vm_disk
    disk = self.client.vcenter.vm.hardware.Disk.create(vm=self.vm, spec=disk_create_spec)
  File "/root/vSphere_sdk_virt_env/lib/python3.5/site-packages/com/vmware/vcenter/vm/hardware_client.py", line 2634, in create
    'spec': spec,
  File "/root/vSphere_sdk_virt_env/lib/python3.5/site-packages/vmware/vapi/bindings/stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/root/vSphere_sdk_virt_env/lib/python3.5/site-packages/vmware/vapi/bindings/stub.py", line 275, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.InvalidArgument: {messages : [LocalizableMessage(default_message="Incompatible device backing specified for device '0'.", args=[], id='vmsg.InvalidDeviceBacking.summary')], data : None}

4. PowerCli command
New-HardDisk -VM RHEL70_thick13  -DiskType RawPhysical -DeviceName /vmfs/devices/disks/eui.57df0280647efa2de9751c5d0000000a

and RDM disk addition though vSphere client work OK and querying the disks shows that I gave correct parameters in the above functions.

Can you advise please what is the problem and how to solve it?
Thanks

## Actual behavior
Get the following exception:
 com.vmware.vapi.std.errors_client.InvalidArgument: {messages : [LocalizableMessage(default_message="Incompatible device backing specified for device '0'.", args=[], id='vmsg.InvalidDeviceBacking.summary')], data : None}
## Expected behavior
Added RDM disk to VM

**Comment by tianhao64** [comment]
@14kosta Apologies for the late response. 

Can you try to comment out "type=Disk.HostBusAdapterType.SCSI," when creating the Disk.CreateSpec?

If it's still not working. Could you please post the stacktrace from /var/log/vmware/vpxd/vpxd.log so we get more info?

**Comment by 14kosta** [comment]
Hi tianhao64,
Commenting out "type=Disk.HostBusAdapterType.SCSI," doesn't help - I get the same error.
Attaching vpxd.log
[vpxd.zip](https://github.com/vmware/vsphere-automation-sdk-python/files/2745545/vpxd.zip)

Thank you

**Comment by tianhao64** [comment]
@14kosta Hmm. the log doesn't have related error message.  Will ask the storage expert to take a look. Meanwhile, can you check this post? https://cormachogan.com/2013/04/08/microsoft-clustering-on-vsphere-incompatible-device-errors/

**Comment by 14kosta** [comment]
Hi tianhao64,
I looked at the sent by you link. My configuration is the following: I have SCSI device /vmfs/devices/disks/eui.57df0280647efa2de9751c5d0000000 that is seen on three ESXi hosts.  Then I attaching it to VM that is on one of ESXi hosts and the command fails thru SDK, but succeeded thru PowerCli and Web client. Situation described in the sent link looks for me  a little bit different.
Thank you

**Comment by tianhao64** [comment]
I filed a SR against the storage team. Will keep you posted. Can you check hostd.log see if you see related error message?

**Comment by 14kosta** [comment]
Command "find / -name hostd" doesn't return any hostd.log on vCenter or ESXi. Where to search for it?
BTW, in debugger I see that the error comes from requests module i.e. really comes from a server side.

**Comment by Pyaray77** [comment]
Modern versions of ESXi keep the hostd.log in /var/run/log.  Generally when you pull down a vm-support, the files will be gzip'ed

**Comment by 14kosta** [comment]
when I run RDM mapping in the file /var/log/hostd.log appears the following:
2019-01-13T08:58:25.889Z info hostd[2099863] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5bdb7b78-27334b79-c9e6-2c600c66a3ff/RHEL70_thick13/RHEL70_thick13.vmx opID=50e9b1cb-01-dc-96e4 user=vpxuser:AUTO01.LOCAL\Administrator] Send config update invoked
2019-01-13T08:58:25.919Z info hostd[2099863] [Originator@6876 sub=Libs opID=50e9b1cb-01-dc-96e4 user=vpxuser:AUTO01.LOCAL\Administrator] DictionaryLoad: Cannot open file "/usr/lib/vmware/config": No such file or directory.
2019-01-13T08:58:25.919Z info hostd[2099863] [Originator@6876 sub=Libs opID=50e9b1cb-01-dc-96e4 user=vpxuser:AUTO01.LOCAL\Administrator] Could not expand environment variable HOME.
2019-01-13T08:58:25.919Z info hostd[2099863] [Originator@6876 sub=Libs opID=50e9b1cb-01-dc-96e4 user=vpxuser:AUTO01.LOCAL\Administrator] DictionaryLoad: Cannot open file "~/.vmware/config": No such file or directory.
2019-01-13T08:58:25.922Z info hostd[2099863] [Originator@6876 sub=Vimsvc.TaskManager opID=50e9b1cb-01-dc-96e4 user=vpxuser:AUTO01.LOCAL\Administrator] Task Completed : haTask-5-vim.VirtualMachine.reconfigure-1121411 Status error
2019-01-13T08:58:25.922Z warning hostd[2099863] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5bdb7b78-27334b79-c9e6-2c600c66a3ff/RHEL70_thick13/RHEL70_thick13.vmx opID=50e9b1cb-01-dc-96e4 user=vpxuser:AUTO01.LOCAL\Administrator] Reconfigure failed
2019-01-13T08:58:33.579Z info hostd[2099318] [Originator@6876 sub=Vimsvc.ha-eventmgr] Event 58743 : Hardware Sensor Status: Processor green, Memory green, Fan green, Voltage green, Temperature green, Power green, System Board green, Battery green, Storage green, Other red
count_events: starting communication with bmc over ipmi driver
count_events: GET_SEL_REPO_INFO returned {version: 0x51, count 909, free 0,add_stamp 0, erase_stamp 0 op_support 143}
IPMI SEL sync took 0 seconds 0 sel records, last 0
2019-01-13T08:58:33.581Z error hostd[2099318] [Originator@6876 sub=Cimsvc] IPMI SEL unavailable
2019-01-13T08:58:33.582Z info hostd[2099870] [Originator@6876 sub=Libs opID=ab7196f3] NetstackInstanceImpl: congestion control algorithm: newreno
[LikewiseGetDomainJoinInfo:354] QueryInformation(): ERROR_FILE_NOT_FOUND (2/0):

**Comment by 14kosta** [comment]
Hi tianhao64,
I run RDM mapping and simultaneously took vpxd.log (attached to this message) and hostd.log 
(see the previous message).
In the current vpxd.log appears  "Incompatible device backing specified for device '0'.":
vim.fault.InvalidDeviceBacking:
--> Result:
--> (vim.fault.InvalidDeviceBacking) {
-->    faultCause = (vmodl.MethodFault) null, 
-->    faultMessage = <unset>, 
-->    property = <unset>, 
-->    deviceIndex = 0
-->    msg = "Incompatible device backing specified for device '0'."
--> }
[vpxd.zip](https://github.com/vmware/vsphere-automation-sdk-python/files/2752969/vpxd.zip)

**Comment by tianhao64** [comment]
No update from the feature team yet. Will ping them again.

**Comment by 14kosta** [comment]
@tianhao64 , thank you!

**Comment by anusha94** [comment]
@tianhao64 
Was there any progress from the feature team?

@14kosta 
Do you know if this issue still exists with the latest SDK?

**Comment by 14kosta** [comment]
Hi.

We don't get any reply from the feature team. Were very disappointed how
Vmware helps their users to resolve the problems concerned with usage of
Vmware sdk. Switched to PowerCli, ported to Linux, which worked fine.

**Comment by anusha94** [comment]
@14kosta 
I am very sorry to hear that. The teams are distributed and features sometimes don't make it to the priority list and are kept hanging. We will try to fix this gap in the future.
Glad you were able to resolve with powercli.
