### ISSUE TITLE
Please update Readme

### ISSUE THREAD

**Issue by cynthia-rempel** [vmware/vsphere-automation-sdk-python#121]
I ran pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file:///build/vsphere-automation-sdk-python/lib
and got errors.

Looked for requirements.txt, found /build/vsphere-automation-sdk-python/

Apparently, I also was supposed to install vapi-client-bindings BEFORE running this command

**Comment by cynthia-rempel** [comment]
Removing the --force-reinstall and removing /lib at the end didn't result in errors

**Comment by tianhao64** [comment]
@cynthia-rempel If you hit error when using pip cmd it usually means a incorrect file url is used. What's the absolute path of your local sdk repo? Can you post the complete cmd output? I assume you are using linux, right?

**Comment by tianhao64** [comment]
Close as not a bug. Please check https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting to see if it can help you resolve your issue.
