### ISSUE TITLE
com.vmware.appliance_client: LocalAccounts.Info(fullname) vs. LocalAccounts.UpdateConfig(full_name) 

### ISSUE THREAD

**Issue by NikolayDachev** [vmware/vsphere-automation-sdk-python#122]
I'm using latest version from github but also in documentations is the same 

Is there any reason why for LocalAccounts.Info we should use (fullname) and for  LocalAccounts.UpdateConfig we should use (full_name)

https://vmware.github.io/vsphere-automation-sdk-python/vsphere/6.7.1/com.vmware.html?highlight=com%20vmware%20appliance_client%20module#module-com.vmware.appliance_client

**Comment by tianhao64** [comment]
@NikolayDachev Thanks for raising this issue. Looks like it's a bug on the LocalAccounts.Info. It supposed to be full_name too. Will file a bug to the team.

**Comment by khayamgondal** [comment]
@tianhao64 is it still open? I can work on it if I can get some guidance.

**Comment by anusha94** [comment]
I believe this was ruled as _not a bug_ by the feature team as the API is already released. I am closing this issue. Feel free to reopen.
