### ISSUE TITLE
can this be configured for flask ?

### ISSUE THREAD

**Issue by dfoley84** [vmware/vsphere-automation-sdk-python#123]
- [ ] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [ ] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [ ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

- python version:

- vSphere version:

- Operating System/Shell (used to run SDK-based apps):

**Comment by tianhao64** [comment]
@dfoley84 Can you be more specific about your question?

**Comment by dfoley84** [comment]
@tianhao64 at the moment i am working on a "Node.js" front end that will link back to Terraform, to give users a GUI interface for requesting vsphere / amazon web service resources. While Terraform is limited with vmware provider, i would like to opt for the same idea for vSphere SDK for python using "Flask" to give users a rich GUI interface for requesting vsphere resources. Since you don't offer a java script version.  

Also what is the difference between this SDK vs PowerCLI for automation ?

**Comment by tianhao64** [comment]
@dfoley84 This sdk has python bindings to vSphere, VMC and NSXT REST APIs. PowerCLI provides cmd link utils to interact with multiple VMware products. Note that at this point majority of the vSphere features are covered by pyVmomi. Automation SDK covers a few new features as well as vCenter VM lifecycle APIs. 
PyVmomi uses vSphere web service APIs which are SOAP based APIs. For more info refer to: https://code.vmware.com/doc/preview?id=4206
vSphere Automation SDKs (python, java, .net, perl, ruby and REST) uses new version REST based APIs. Some new features like Tagging, Content Library,
Appliance Management, NSX and VMware Cloud on AWS console APIs are only available through the Automation SDKs. Some existing SOAP based APIs, such as VM lifecycle and VC inventory APIs are also re-designed to support REST. For more info please see: https://vmware.github.io/vsphere-automation-sdk/. Here is talk from @kmruddy about the new REST API: https://www.youtube.com/watch?v=nr3pJovtbzM
