### ISSUE TITLE
how to get '_moId'  and the IP of the vcenter from vsphere_client

### ISSUE THREAD

**Issue by shekharHPE** [vmware/vsphere-automation-sdk-python#131]
I created a vsphere_client using 
create_vsphere_client(server=<vcenter-ip>, username= <usr-name>, password=<pwd>, session=session)
And I am trying to get the '_moId' of the vcenter and the IP associated with the vcenter. 
I know that I would provide <vcenter-ip> as a parameter while creating the vsphere_client, but still I need the information regarding the IP and _moId from the vsphere_client.

Reason why I need '_moId' :  I have fetched all the tags and associated _moIds, now I am mapping all the _moIds to appropriate VMs/Datacenters/Hosts/Vcenter (itself)

Request you to solved the issue ASAP 
Awaiting your response.

**Comment by tianhao64** [comment]
@shekharHPE You can get moid for objects inside a vCenter, I don't think vCenter itself has moid though. You will pass vCenter hostname/ip when creating a vSphere_client, why you need to get IP again? 
You can get vCenter metadata using appliance API: 
vsphere_client.appliance.system.Version.get()
VersionStruct(version='6.7.0.12000', product='VMware vCenter Server Appliance', build='8832884', type='vCenter Server with an embedded Platform Services Controller', summary='Patch forVMware vCenter Server Appliance 6.7.0', releasedate='June 28, 2018', install_time='2018-07-02T18:20:11 UTC')

**Comment by shekharHPE** [comment]
1. I assigned a tag to Vcenter in WebClient.
2. from vsphere_client.tagging API, I got the following: 
the "group-d1" is the _moId for vcenter itself.

    "group-d1": {
        "B1": "B"
    },

In my code, I am trying to associate and verify if the tags I assigned in WebClient are in sync with the tags I receive from vshpere_client.tagging
All the other tags and moIds for VMs are accounted for, but not for vcenter itself.
Thus I need to get the moId of the vcenter..so I can verify if the moID returned by the tag matches with the moID of the vcenter and verify the tag assigned to it. 

I am not much worried about the IP, I mostly need information regarding the moId of the vcenter.

**Comment by shekharHPE** [comment]
--- FYI
    "group-d1": {
    "B1": "B"
    },
here group-d1  is the moID and "B1" is the tag_name and "B" is the category_name 
I have modified response from vsphere_client.tagging  to get the JSON like above.

**Comment by tianhao64** [comment]
Is 'group-d1' moid of vCenter or rootFolder? You can verify it vcenter_ip/mob
So you are not seeing the tag associated to "group-d1"? Can you share your code and steps to reproduce?

**Comment by tianhao64** [comment]
@shekharHPE I am closing this for now. Please provide more info if there still an issue.
