### ISSUE TITLE
iso_mount throws exception when trying to mount

### ISSUE THREAD

**Issue by abshelto** [vmware/vsphere-automation-sdk-python#132]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 
pyvmomi               6.7.1.2018.12
vapi-client-bindings  1.5.0
vapi-common-client    2.10.2
vapi-runtime          2.10.2
vmc-app-python-sdk    2.3.0.0.2.11053635
vmc-client-bindings   1.3.1

- python version:
python 3.7.0

- vSphere version:
6.7 update 1

- Operating System/Shell (used to run SDK-based apps):

centos 7/bash

## Steps or code snippet to reproduce

running the sample iso_mount.py file by:

python3 iso_mount.py -s vcenter-fqdn -u user -p password -v --datastorename vsan-hx --vmname test-linux-from-packer

## Actual behavior

server: vcenter
Datastore MoId: datastore-1597
Local library created, ID: 7bb61fb6-00d8-4d80-94b1-0411e4a5b89d
Library item created id: 7222b04d-2249-4fd6-a12f-659b9589df47
Uploaded iso file to library item 7222b04d-2249-4fd6-a12f-659b9589df47
Found VM 'test-linux-from-packer' (vm-2116)
Traceback (most recent call last):
  File "/home/user/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 79, in run
    attr()  # calling the method
  File "iso_mount.py", line 92, in _execute
    device_id = self.client.iso_service.mount(library_item_id, vm_id)
  File "/usr/local/lib/python3.7/site-packages/com/vmware/vcenter/iso_client.py", line 99, in mount
    'vm': vm,
  File "/usr/local/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 275, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.InternalServerError: {messages : [LocalizableMessage(id='vapi.bindings.method.impl.unexpected', default_message='Provider method implementation threw unexpected exception: com.vmware.vapi.std.errors.InternalServerError', args=['com.vmware.vapi.std.errors.InternalServerError']), LocalizableMessage(id='com.vmware.vdcs.iso-main.vm_reconfigure_failed_for_iso_mount', default_message='File [vsan-hx] contentlib-7bb61fb6-00d8-4d80-94b1-0411e4a5b89d/7222b04d-2249-4fd6-a12f-659b9589df47/CentOS-7-x86_64-Minimal-1810_3168940e-e1c6-4fe2-8868-2c2651243a2e.iso could not be mounted on the virtual machine test-linux-from-packer due to VirtualMachine reconfiguration failure.', args=['[vsan-hx] contentlib-7bb61fb6-00d8-4d80-94b1-0411e4a5b89d/7222b04d-2249-4fd6-a12f-659b9589df47/CentOS-7-x86_64-Minimal-1810_3168940e-e1c6-4fe2-8868-2c2651243a2e.iso', 'test-linux-from-packer'])], data : None}
Traceback (most recent call last):
  File "/home/user/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 79, in run
    attr()  # calling the method
  File "iso_mount.py", line 92, in _execute
    device_id = self.client.iso_service.mount(library_item_id, vm_id)
  File "/usr/local/lib/python3.7/site-packages/com/vmware/vcenter/iso_client.py", line 99, in mount
    'vm': vm,
  File "/usr/local/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 275, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.InternalServerError: {messages : [LocalizableMessage(id='vapi.bindings.method.impl.unexpected', default_message='Provider method implementation threw unexpected exception: com.vmware.vapi.std.errors.InternalServerError', args=['com.vmware.vapi.std.errors.InternalServerError']), LocalizableMessage(id='com.vmware.vdcs.iso-main.vm_reconfigure_failed_for_iso_mount', default_message='File [vsan-hx] contentlib-7bb61fb6-00d8-4d80-94b1-0411e4a5b89d/7222b04d-2249-4fd6-a12f-659b9589df47/CentOS-7-x86_64-Minimal-1810_3168940e-e1c6-4fe2-8868-2c2651243a2e.iso could not be mounted on the virtual machine test-linux-from-packer due to VirtualMachine reconfiguration failure.', args=['[vsan-hx] contentlib-7bb61fb6-00d8-4d80-94b1-0411e4a5b89d/7222b04d-2249-4fd6-a12f-659b9589df47/CentOS-7-x86_64-Minimal-1810_3168940e-e1c6-4fe2-8868-2c2651243a2e.iso', 'test-linux-from-packer'])], data : None}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "iso_mount.py", line 114, in <module>
    main()
  File "iso_mount.py", line 110, in main
    iso_mount_sample.main()
  File "/home/user/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 97, in main
    self.run()
  File "/home/user/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 85, in run
    raise Exception(e)
Exception: {messages : [LocalizableMessage(id='vapi.bindings.method.impl.unexpected', default_message='Provider method implementation threw unexpected exception: com.vmware.vapi.std.errors.InternalServerError', args=['com.vmware.vapi.std.errors.InternalServerError']), LocalizableMessage(id='com.vmware.vdcs.iso-main.vm_reconfigure_failed_for_iso_mount', default_message='File [vsan-hx] contentlib-7bb61fb6-00d8-4d80-94b1-0411e4a5b89d/7222b04d-2249-4fd6-a12f-659b9589df47/CentOS-7-x86_64-Minimal-1810_3168940e-e1c6-4fe2-8868-2c2651243a2e.iso could not be mounted on the virtual machine test-linux-from-packer due to VirtualMachine reconfiguration failure.', args=['[vsan-hx] contentlib-7bb61fb6-00d8-4d80-94b1-0411e4a5b89d/7222b04d-2249-4fd6-a12f-659b9589df47/CentOS-7-x86_64-Minimal-1810_3168940e-e1c6-4fe2-8868-2c2651243a2e.iso', 'test-linux-from-packer'])], data : None}
disconnecting the session

## Expected behavior

It keeps failing at the mounting of the ISO. I can see in the datastore that the folder is created with the iso in there. I saw the iso uploaded successfully, adds the cdrom, connects the cdrom and actually connects the iso from the content library after it errors out, but then the python script errors out with the error above.

**Comment by tianhao64** [comment]
I just submitted a change so the sample should fail right away when exception occurs. I am talking to the content library team about the actually exception now.

**Comment by tianhao64** [comment]
@abshelto
The iso service (which provides mount operation) requires:
- Content library be backed by datastore and not NFS. A datastore backed by NFS should be fine.
- The datastore of the content library where the iso item is mounted be accessible from the host or cluster on which the vm resides.

Can you check if these two requirements are satisfied? Were you able to mount the iso from UI?

**Comment by tianhao64** [comment]
Close this for now. @abshelto Please reopen is the issue still exists.

**Comment by Nick-Cool** [comment]
I ran into the exact same issue...My content library is backed by vSAN datastore. Is there a solution to this problem
