### ISSUE TITLE
Simple way to find the cluster a vm is on at the moment?

### ISSUE THREAD

**Issue by klainn** [vmware/vsphere-automation-sdk-python#141]
- [X] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [X] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [X] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 
vapi-client-bindings  1.5.0
vapi-common-client    2.10.2
vapi-runtime          2.10.2
vmc-app-python-sdk    2.3.0.0.2.11053635
vmc-client-bindings   1.3.1

- python version:
Python 3.6.4

- vSphere version:
Version 6.5.0.20000 Build 9451637

- Operating System/Shell (used to run SDK-based apps):
Windows 7

## Steps or code snippet to reproduce
Looking for a code snippet.

## Actual behavior
None

## Expected behavior
returns cluster name when given vm name as key

I'm looking for something that has to be available I'm just not finding it in the docs or going through the python code. I want to give a virtual machine name (human given not the vm-###) and be able to tell what cluster it is currently residing on.

**Comment by tianhao64** [comment]
@klainn This should work:
import requests
import urllib3
from vmware.vapi.vsphere.client import create_vsphere_client
from com.vmware.vcenter_client import VM

vm_name = "windows10"

session = requests.session()
session.verify = False
client = create_vsphere_client(server='', username='', password='', session=session)

clusters = client.vcenter.Cluster.list()

for cluster in clusters:
    vms = client.vcenter.VM.list(VM.FilterSpec(clusters={cluster.cluster}))
    if vm_name in [vm.name for vm in vms]:
        break

print(cluster.name)

**Comment by klainn** [comment]
This led me down the right path. My end product is a little different but I think it'll work for what I need. 

Thanks much.
