### ISSUE TITLE
com.vmware.api.vcenter.vm.too_many_matches when looking at all vms on a cluster

### ISSUE THREAD

**Issue by klainn** [vmware/vsphere-automation-sdk-python#142]
- [X] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [X] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [X] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 
vapi-client-bindings 1.5.0
vapi-common-client 2.10.2
vapi-runtime 2.10.2
vmc-app-python-sdk 2.3.0.0.2.11053635
vmc-client-bindings 1.3.1

- python version:
Python 3.6.4

- vSphere version:
Version 6.5.0.20000 Build 9451637

- Operating System/Shell (used to run SDK-based apps):
Windows 7

## Steps or code snippet to reproduce
```
cluster_names = {'domain-c28004'}

vms_list = vsphere_client.vcenter.VM.list(VM.FilterSpec(clusters=cluster_names))
```

## Actual behavior
Looping through all the clusters to find the vm's on that cluster as such:

And I am getting the:
com.vmware.vapi.std.errors_client.UnableToAllocateResource: {messages : [LocalizableMessage(id='com.vmware.api.vcenter.vm.too_many_matches', default_message='Too many virtual machines. Add more filter criteria to reduce the number.', args=[])], data : None}

Doesn't happen in our lab either, but there's only a handful of vm's there vs an enterprise worth in the production vm environment. The cluster this seems to choke on has 152 virtual machines on it.

## Expected behavior
Returns list of all vm's on requested cluster regardless of count.

**Comment by tianhao64** [comment]
@klainn list() returns maximum 1000 objects as stated in the API doc: https://vmware.github.io/vsphere-automation-sdk-python/vsphere/6.7.1/com.vmware.html#com.vmware.vcenter_client.VM.list. The filter spec takes a list of cluster IDs, not names. You can only use vm names in the VM list() filter spec. Here is an example how to get cluster ID: https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/vcenter/helper/cluster_helper.py. Can you confirm if you have only 152 VMs in your vCenter? If you have more than 1000 vms, please use more filters to reduce the scope.

**Comment by klainn** [comment]
But that's the problem. The project requirement is that if a VM exists in the vcenter instance I'm working with, I need to be able to see it regardless of any filter conditions. The only filter condition the business is interested in is exists==true.

Do you have a suggestion on how to use filters but still get every virtual machine?

**Comment by tianhao64** [comment]
I will discuss this use case with the team.
Meanwhile, are all vms in the same container (cluster/resource_pool/folder/datastore/folder)? Do you organize them in any ways? If so, then probably you can iterate the container and then list vms in each container?

**Comment by klainn** [comment]
They are sorted by Datacenter, then folders. The one datacenter I'm struggling with has 7300 vms on it and I can't find a filter that searches something that returns 1000 or fewer. In this particular datacenter, one folder has 5100 vms alone. Multiple clusters in that folder have more than 1000 vms, etc. 

A esx host shouldn't have more than 1000 machines on it. That seems highly unlikely. I see there's a Hosts.list() function but I'm not immediately seeing a way to list all the vms on a esx host. Seems like it should be possible though.

**Comment by klainn** [comment]
Ok, so maybe not.

My end goal is to produce a simple list that will update a table that has 2 columns, cluster_name, virtual_machine_name.

I can get all the vms by querying all the hosts. But I'm struggling to get the cluster the vm is on using your code from above, I still have to search clusters with more than 1000 machines and I get the original error.

This is the code I'm using. It feels like this should be more easily done. This code produces the too many vm's error from above.

```
import requests
import urllib3
from vmware.vapi.vsphere.client import create_vsphere_client
from com.vmware.vcenter_client import VM
import sys
 
def createConnection():
    session = requests.session()
    session.verify = False
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
 
    vsphere_client = create_vsphere_client(
        server='<redacted>',
        username='<redacted>',
        password='<redacted>',
        session=session
    )
 
    return vsphere_client
 
 
def getVMSonHost():
    vsphere_client = createConnection()
    # Get all Hosts
    host_list = []
    all_hosts = vsphere_client.vcenter.Host.list()
    for hst in all_hosts:
        host_list.append(hst.host)
 
    # Get all VMs on Host
    vm_list = []
    for esx_host in host_list:
        print('Looking in: {}'.format(esx_host))
        vms = vsphere_client.vcenter.VM.list(VM.FilterSpec(hosts={esx_host}))
        vm_list.append([vm.name for vm in vms])
 
    # Try to get cluster of VM
    vm_cluster_list = []
    all_clusters = vsphere_client.vcenter.Cluster.list()
 
    for vm_name in vm_list:
        for cluster in all_clusters:
            vms = vsphere_client.vcenter.VM.list(VM.FilterSpec(clusters={cluster.cluster}))
            if vm_name in [vm.name for vm in vms]:
                print('{} on {}'.format(vm_name, cluster.name))
                vm_cluster_list.extend([cluster.name, vm_name])
                break
    return vm_cluster_list
 
 
giant_vm_list = getVMSonHost()
print(giant_vm_list)
```

The Error:
```

Traceback (most recent call last):
  File "C:/Users/<me>/PycharmProjects/vmware_api_test/filter_vms_by_esx_host.py", line 51, in <module>
    giant_vm_list = getVMSonHost()
  File "C:/Users/<me>/PycharmProjects/vmware_api_test/filter_vms_by_esx_host.py", line 43, in getVMSonHost
    vms = vsphere_client.vcenter.VM.list(VM.FilterSpec(clusters={cluster.cluster}))
  File "C:\Users\<me>\PycharmProjects\vmware_api_test\venv\lib\site-packages\com\vmware\vcenter_client.py", line 3178, in list
    'filter': filter,
  File "C:\Users\<me>\PycharmProjects\vmware_api_test\venv\lib\site-packages\vmware\vapi\bindings\stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "C:\Users\<me>\PycharmProjects\vmware_api_test\venv\lib\site-packages\vmware\vapi\bindings\stub.py", line 275, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.UnableToAllocateResource: {messages : [LocalizableMessage(id='com.vmware.api.vcenter.vm.too_many_matches', default_message='Too many virtual machines. Add more filter criteria to reduce the number.', args=[])], data : None}
```

Has to be a better way to get this than the path I'm going down.

**Comment by tianhao64** [comment]
How about iterate clusters and then hosts inside each cluster?
```
import requests
import urllib3
from vmware.vapi.vsphere.client import create_vsphere_client
from com.vmware.vcenter_client import VM, Host
import sys
 
def createConnection():
    session = requests.session()
    session.verify = False
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
 
    vsphere_client = create_vsphere_client(
        server='',
        username='',
        password='',
        session=session
    )
 
    return vsphere_client
 
 
def getVMSonHost():
    vsphere_client = createConnection()

    vm_cluster_list = []
    clusters = vsphere_client.vcenter.Cluster.list()
    for cluster_summary in clusters:
        hosts = vsphere_client.vcenter.Host.list(Host.FilterSpec(clusters={cluster_summary.cluster}))
        for host_summary in hosts:
            vms = vsphere_client.vcenter.VM.list(VM.FilterSpec(hosts={host_summary.host}))
            for vm in vms:
                vm_cluster_list.append([cluster_summary.name, vm.name])
    
    return vm_cluster_list

giant_vm_list = getVMSonHost()
from pprint import pprint
pprint(giant_vm_list)
```

**Comment by klainn** [comment]
Yeah that seems solid. The result count is a little different but maybe not a big deal. Very cool.
