### ISSUE TITLE
How to get disk, memory usage of each vm

### ISSUE THREAD

**Issue by JamesHuangUC** [vmware/vsphere-automation-sdk-python#147]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [ ] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 
pyvmomi                6.7.1.2018.12
vapi-client-bindings   1.5.0
vapi-common-client     2.10.2
vapi-runtime           2.10.2
vmc-app-python-sdk     2.3.0.0.2.11053635
vmc-client-bindings    1.3.1

- python version:
Python 3.7.3

- vSphere version:
Version 6.5.0.13000

- Operating System/Shell (used to run SDK-based apps):
Mac OS 10.13.6

## Steps or code snippet to reproduce
```
vsphere_client = createConnection()
print(vsphere_client.vcenter.VM.list())
```

## Actual behavior
Returning Summary of each vm, which includes vm, name, power_state, cpu_count, memory_size_mib.

## Expected behavior
I want to get the disk, memory usage of each VM.
Instead of returning `VM.Summary`, how can I return some more detail info of each vm, for example maybe returning `VM.Info`?

**Comment by tianhao64** [comment]
@JamesHuangUC vsphere_client.vcenter.VM.get('vm_id') gives below info:

vc_client.vcenter.VM.get('vm-71')
Info(guest_os=GuestOS(string='WINDOWS_9_64'), name='Sample_Exhaustive_VM_for_Simple_Testbed', power_state=State(string='POWERED_OFF'), hardware=Info(version=Version(string='VMX_11'), upgrade_policy=UpgradePolicy(string='NEVER'), upgrade_version=None, upgrade_status=UpgradeStatus(string='NONE'), upgrade_error=None), boot=Info(type=Type(string='BIOS'), efi_legacy_boot=None, network_protocol=None, delay=0, retry=False, retry_delay=10000, enter_setup_mode=False), boot_devices=[Entry(type=Type(string='CDROM'), nic=None, disks=None), Entry(type=Type(string='DISK'), nic=None, disks=['2000', '2001', '2002']), Entry(type=Type(string='ETHERNET'), nic='4000', disks=None)], cpu=Info(count=2, cores_per_socket=1, hot_add_enabled=False, hot_remove_enabled=False), memory=Info(size_mib=2048, hot_add_enabled=False, hot_add_increment_size_mib=None, hot_add_limit_mib=None), disks={'2002': Info(label='Hard disk 3', type=HostBusAdapterType(string='SCSI'), ide=None, scsi=ScsiAddressInfo(bus=0, unit=2), sata=None, backing=BackingInfo(type=BackingType(string='VMDK_FILE'), vmdk_file='[Shared_NFS_Volume] Sample_Exhaustive_VM_for_Simple_Testbed/data2.vmdk'), capacity=10737418240), '2001': Info(label='Hard disk 2', type=HostBusAdapterType(string='SCSI'), ide=None, scsi=ScsiAddressInfo(bus=0, unit=1), sata=None, backing=BackingInfo(type=BackingType(string='VMDK_FILE'), vmdk_file='[Shared_NFS_Volume] Sample_Exhaustive_VM_for_Simple_Testbed/data1.vmdk'), capacity=10737418240), '2000': Info(label='Hard disk 1', type=HostBusAdapterType(string='SCSI'), ide=None, scsi=ScsiAddressInfo(bus=0, unit=0), sata=None, backing=BackingInfo(type=BackingType(string='VMDK_FILE'), vmdk_file='[Shared_NFS_Volume] Sample_Exhaustive_VM_for_Simple_Testbed/boot.vmdk'), capacity=42949672960)}, nics={'4000': Info(label='Network adapter 1', type=EmulationType(string='E1000E'), upt_compatibility_enabled=None, mac_type=MacAddressType(string='MANUAL'), mac_address='11:23:58:13:21:34', pci_slot_number=None, wake_on_lan_enabled=False, backing=BackingInfo(type=BackingType(string='STANDARD_PORTGROUP'), network='network-63', network_name='VM Network', host_device=None, distributed_switch_uuid=None, distributed_port=None, connection_cookie=None, opaque_network_type=None, opaque_network_id=None), state=ConnectionState(string='NOT_CONNECTED'), start_connected=True, allow_guest_control=False), '4001': Info(label='Network adapter 2', type=EmulationType(string='E1000E'), upt_compatibility_enabled=None, mac_type=MacAddressType(string='ASSIGNED'), mac_address='00:50:56:ba:19:3e', pci_slot_number=None, wake_on_lan_enabled=False, backing=BackingInfo(type=BackingType(string='DISTRIBUTED_PORTGROUP'), network='dvportgroup-68', network_name=None, host_device=None, distributed_switch_uuid='50 3a 74 c0 b2 b1 91 9a-11 32 44 94 cd 94 e1 72', distributed_port='4', connection_cookie=1788039532, opaque_network_type=None, opaque_network_id=None), state=ConnectionState(string='NOT_CONNECTED'), start_connected=True, allow_guest_control=False)}, cdroms={'16000': Info(type=HostBusAdapterType(string='SATA'), label='CD/DVD drive 1', ide=None, sata=SataAddressInfo(bus=0, unit=0), backing=BackingInfo(type=BackingType(string='ISO_FILE'), iso_file='[Shared_NFS_Volume] Sample_Backends/iso/photonOS.iso', host_device=None, auto_detect=None, device_access_type=None), state=ConnectionState(string='NOT_CONNECTED'), start_connected=True, allow_guest_control=False)}, floppies={'8000': Info(label='Floppy drive 1', backing=BackingInfo(type=BackingType(string='CLIENT_DEVICE'), image_file=None, host_device=None, auto_detect=None), state=ConnectionState(string='NOT_CONNECTED'), start_connected=False, allow_guest_control=False)}, parallel_ports={'10000': Info(label='Parallel port 1', backing=BackingInfo(type=BackingType(string='HOST_DEVICE'), file=None, host_device='', auto_detect=True), state=ConnectionState(string='NOT_CONNECTED'), start_connected=False, allow_guest_control=False)}, serial_ports={}, sata_adapters={'15000': Info(label='SATA controller 0', type=Type(string='AHCI'), bus=0, pci_slot_number=None)}, scsi_adapters={'1000': Info(label='SCSI controller 0', type=Type(string='LSILOGICSAS'), scsi=ScsiAddressInfo(bus=0, unit=7), pci_slot_number=None, sharing=Sharing(string='NONE'))})

**Comment by JamesHuangUC** [comment]
👍 thank you so much!

**Comment by JamesHuangUC** [comment]
Hi @tianhao64 I can see `VM.get` can return me a bunch of useful information, but is it possible also return me how many memory is active and how many disk space is used?

**Comment by tianhao64** [comment]
@JamesHuangUC guest runtime info is not support in this sdk yet. Please use pyvmomi for now.

**Comment by JamesHuangUC** [comment]
Thank you @tianhao64, I will take a look at it.

**Comment by MrPippin66** [comment]
Can this be expanded to include providing API for getting current CPU use, memory use, disk throughput and network throughput for hosts?

Or would this need a separate feature request?
