### ISSUE TITLE
VM Power On 

### ISSUE THREAD

**Issue by tahamian** [vmware/vsphere-automation-sdk-python#160]
- [ ] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [ ] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [ ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

- python version:

- vSphere version:

- Operating System/Shell (used to run SDK-based apps):

## Steps or code snippet to reproduce
 <a href="https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/vcenter/vm/power.py"> From this sample</a>
```
 # Power on the vm
    print('# Example: Power on the vm')
    client.vcenter.vm.Power.start(vm)
    print('vm.Power.start({})'.format(vm))
```
## Actual behavior

there is no operation start in guest_client.py

**Comment by tianhao64** [comment]
@tahamian Can you elaborate what's the issue and what is the expectation?

**Comment by tahamian** [comment]
oh, I was just thinking if we use
```
from vmware.vapi.vsphere.client import create_vsphere_client
```
and create a connection, we can use the client  connection to power on the VM, but if we use

```
from com.vmware.vcenter.vm.guest_client import Power
```

and try and create a stub config, there is way to power on the VM,

from guest_client.py

```
 operations = {
            'get': {
                'input_type': get_input_type,
                'output_type': type.ReferenceType(__name__, 'Power.Info'),
                'errors': get_error_dict,
                'input_value_validator_list': get_input_value_validator_list,
                'output_validator_list': get_output_validator_list,
                'task_type': TaskType.NONE,
            },
            'shutdown': {
                'input_type': shutdown_input_type,
                'output_type': type.VoidType(),
                'errors': shutdown_error_dict,
                'input_value_validator_list': shutdown_input_value_validator_list,
                'output_validator_list': shutdown_output_validator_list,
                'task_type': TaskType.NONE,
            },
            'reboot': {
                'input_type': reboot_input_type,
                'output_type': type.VoidType(),
                'errors': reboot_error_dict,
                'input_value_validator_list': reboot_input_value_validator_list,
                'output_validator_list': reboot_output_validator_list,
                'task_type': TaskType.NONE,
            },
            'standby': {
                'input_type': standby_input_type,
                'output_type': type.VoidType(),
                'errors': standby_error_dict,
                'input_value_validator_list': standby_input_value_validator_list,
                'output_validator_list': standby_output_validator_list,
                'task_type': TaskType.NONE,
            },
```
its just kind of inconsistent, shouldnt we be able to power on VM using the both methods of connection?
Thats all i was trying to point out

**Comment by tahamian** [comment]
sorry this i realized what I was trying to do, I was trying to use the stub configuration for Power, 
```
from com.vmware.vcenter.vm.guest_client import Power
```
and after looking at the api documentation, there is no way to power on the VM, but that is not the case if we use 
```
from vmware.vapi.vsphere.client import create_vsphere_client
```

we are able to power on the VM, thought it might have been an inconsistency, but the api does not allow to power on vm.

Thanks
