### ISSUE TITLE
Is there anyway you can create package for pip install to use directly

### ISSUE THREAD

**Issue by xjanechen** [vmware/vsphere-automation-sdk-python#161]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

- python version:

- vSphere version:

- Operating System/Shell (used to run SDK-based apps):

## Actual behavior
For installation, we need to git clone and then pip install from local copy. such as:
git clone https://github.com/vmware/vsphere-automation-sdk-python.git
cd vsphere-automation-sdk-python
pip install --upgrade -r requirements.txt --extra-index-url file:///<absolute_path_to_sdk>/lib

## Expected behavior
I would like to see it as installable package so I can run a simple command to install it. I believe this is industry standard. For example: 
pip install vsphere-automation-sdk-python

**Comment by khnazaretyan** [comment]
Hi, I guess this issue overlaps with #38 which is in discussion at this moment.

**Comment by xjanechen** [comment]
It works like a charm. Thanks.
