### ISSUE TITLE
How to get vCenter appliance (VCSA) disk usage by pyvmomi for Vcenter 6.0 or 6.5 or 6.7. Is there is way we can do this in Vcenter 6.0

### ISSUE THREAD

**Issue by Imranatnisum** [vmware/vsphere-automation-sdk-python#162]
## Environment

- python version:
3.7
- vSphere version:
6.0, 6.5 and 6.7
- Operating System/Shell (used to run SDK-based apps):
Mac os

**Comment by tianhao64** [comment]
@Imranatnisum You want to query vm disk usage? or datastore usage in vCenter? Please provide more info about what you need.

**Comment by tianhao64** [comment]
Closing due to lack of info. It also seems to be a pyvmomi question
