### ISSUE TITLE
Datastore Over Provisioning

### ISSUE THREAD

**Issue by Imranatnisum** [vmware/vsphere-automation-sdk-python#163]
Do we have some way to get Datastore Over Provisioning

python version:
3.7
vSphere version:
6.0, 6.5 and 6.7
Operating System/Shell (used to run SDK-based apps):
Mac os

**Comment by tianhao64** [comment]
@Imranatnisum Could you please clarify your question? Are you asking about a specific API usage?

**Comment by rchadalawada** [comment]
Closing as there has been no update from filer in 6 months.
