### ISSUE TITLE
support newer versions for requests and pyOpenSSL

### ISSUE THREAD

**Issue by abhiraut** [vmware/vsphere-automation-sdk-python#186]
Can we update requirements for vapi-runtime to support newer requests and pyOpenSSL versions. Perhaps update it to be requests >=2.6.0 and pyOpenSSL >=0.15.1

**Comment by tianhao64** [comment]
The vapi runtime package you are referring is an old one. Please stop using it. It's not uploaded by vmware and it's not supported. 
The dependencies versions are the min working versions. You are free to update individual packages yourself. If we require latest dependencies, it may conflicts with other libraries in your same virtual env.
