### ISSUE TITLE
Why is it a minimum of 3 hosts for VMC SDDCs?

### ISSUE THREAD

**Issue by gamename** [vmware/vsphere-automation-sdk-python#192]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

nsx-vmc-aws-integration-python-sdk 2.3.0.0.3.13851140
nsx-vmc-policy-python-sdk          2.3.0.0.3.13851140
pyvmomi                            6.7.3             
vapi-client-bindings               3.1.0             
vapi-common-client                 2.12.0            
vapi-runtime                       2.12.0            
vmc-client-bindings                1.12.0            
vmc-draas-client-bindings          1.0.0             
vSphere-Automation-SDK             1.6.0             

- python version:

Python 3.7.4

- vSphere version:

- Operating System/Shell (used to run SDK-based apps):

## Steps or code snippet to reproduce
I modified `sddc_crud.py` to accept a variable number of hosts.  When I tried to create an SDDC with just 1 host, I get the following error:
```
Traceback (most recent call last):
  File "./samples/vmc/sddc/sddc_crud.py", line 229, in <module>
    main()
  File "./samples/vmc/sddc/sddc_crud.py", line 221, in main
    sddc_operations.create_sddc()
  File "./samples/vmc/sddc/sddc_crud.py", line 152, in create_sddc
    raise Exception(error_response.error_messages)
Exception: ['Sddc provisioning requires a minimum of 3 hosts.']
```
This seems arbitrary.  Its perfectly possible to start a 1 host SDDC manually.  Why not via the API as well? Remember that the difference between 1 and 3 hosts is a lot of money to the user.  It would be really nice if we could avoid considerable costs by being able to implement single-host configurations.

**Comment by jmh666** [comment]
[seems relevant](https://docs.vmware.com/en/VMware-Cloud-on-AWS/services/com.vmware.vmc-aws-operations/GUID-10A0804B-04F4-4B8A-9EBA-85169F533223.html), but still arbitrary

**Comment by tianhao64** [comment]
@gamename You should be able to create a one node SDDC for evaluation if you pass sddc_type parameter with value '1NODE'.

**Comment by gamename** [comment]
@tianhao64  Thanks! That worked.
