### ISSUE TITLE
 ERROR: Could not find a version that satisfies the requirement vmc-client-bindings (from -r requirements.txt (line 6)) (from versions: none)

### ISSUE THREAD

**Issue by kevink2017CB** [vmware/vsphere-automation-sdk-python#194]
i have try pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file://$PWD/lib，but still  ERROR: Could not find a version that satisfies the requirement vmc-client-bindings (from -r requirements.txt (line 6)) (from versions: none).the content of requirements.txt is "lxml >= 4.3.0
pyVmomi >= 6.7
suds ; python_version < '3'
suds-jurko ; python_version >= '3.0'
vapi-client-bindings == 2.5.0
vmc-client-bindings 
nsx-python-sdk
nsx-policy-python-sdk
nsx-vmc-policy-python-sdk
nsx-vmc-aws-integration-python-sdk
vmc-draas-client-bindings
"

**Comment by jobingeo** [comment]
What is your pip version?

**Comment by gregorydulin** [comment]
I just got this error too.
```
# pip --version
pip 9.0.1 from /usr/local/share/applications/ansible/lib/python2.7/site-packages (python 2.7)
```

**Comment by gregorydulin** [comment]
Might be related to https://github.com/vmware/vsphere-automation-sdk-python/issues/195.  My pip is old...  I'm seeing if I can use an upgraded pip.

**Comment by gregorydulin** [comment]
Upgrading pip resolved this issue for me.

I also specified the current latest tag, vs. whatever git defaults to:
````
pip install --upgrade "git+https://github.com/vmware/vsphere-automation-sdk-python.git@v6.9.1"
```

I'm not sure if that was necessary.

**Comment by jobingeo** [comment]
Look like this issue is related to  https://github.com/vmware/vsphere-automation-sdk-python/issues/195 , as pip upgrade resolved the issue. Thanks @gregorydulin 

Specifying tag is not necessary, unless you need any specific SDK release (tags)
