### ISSUE TITLE
setup.py version number != release version

### ISSUE THREAD

**Issue by JosephHobbs** [vmware/vsphere-automation-sdk-python#200]
While installing the SDK for Python I noticed that the 'release' version here (v6.9.1) does not match the version reported via pip (1.5.0).  Is this intentional?

```
# pip list | grep vSphere
vSphere-Automation-SDK             1.5.0              /opt/ansible/venv/blah/src/vsphere-automation-sdk
```

contents of setup.py within tag v6.9.1.

```
setup(name='vSphere Automation SDK',
      version='1.5.0',
```

Should these versions be kept in sync?

Thanks!

**Comment by anusha94** [comment]
@JosephHobbs 

I think they should be in sync. Are you seeing a mismatch? I am sure I understood this correctly.

**Comment by kunalpmj** [comment]
The installed versions match the version listed from pip
