### ISSUE TITLE
Local installation of SDK fails to process the dependencies

### ISSUE THREAD

**Issue by pgbidkar** [vmware/vsphere-automation-sdk-python#208]
- [ x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x ] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 
1.21.0

- python version:
3.7

- vSphere version:
NA

- Operating System/Shell (used to run SDK-based apps):
Mac
RHEL

## Steps or code snippet to reproduce
Download SDK from link https://github.com/vmware/vsphere-automation-sdk-python/archive/master.zip and extract
CD to extracted folder
Run command $python setup.py install

## Actual behavior
SDK installation is failing with error

```
Searching for vmc-draas-client-bindings@ file://localhost//Users/pbidkar/Downloads/vsphere-automation-sdk-python-master/lib/vmc-draas-client-bindings/vmc_draas_client_bindings-1.3.0-py2.py3-none-any.whl
Reading https://pypi.org/simple/vmc-draas-client-bindings/
Couldn't find index page for 'vmc-draas-client-bindings' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for vmc-draas-client-bindings@ file://localhost//Users/pbidkar/Downloads/vsphere-automation-sdk-python-master/lib/vmc-draas-client-bindings/vmc_draas_client_bindings-1.3.0-py2.py3-none-any.whl
error: Could not find suitable distribution for Requirement.parse('vmc-draas-client-bindings@ file://localhost//Users/pbidkar/Downloads/vsphere-automation-sdk-python-master/lib/vmc-draas-client-bindings/vmc_draas_client_bindings-1.3.0-py2.py3-none-any.whl')

```
This issue seen for all the dependent packages. Tried deleting one by one from setup.py file 

## Expected behavior
SDK should get installed with all dependencies

**Comment by anusha94** [comment]
Here is the github issue explaining why python setup.py does/will not work - https://github.com/pypa/setuptools/issues/1983

I will provide alternate command to install the automation-sdk dependencies, however, the other dependencies and latest pip/setuptools version are a prerequisite

**Comment by anusha94** [comment]
I believe this is the best way to install this SDK currently - https://github.com/vmware/vsphere-automation-sdk-python#installing-required-python-packages

Else, if you want to install locally, I'd suggest downloading the `.whl` files and install them in the right dependency order.
