### ISSUE TITLE
Getting an error `ImportError: No module named vapi.vsphere.client` even if we install the library in anyways.

### ISSUE THREAD

**Issue by vishalxebia** [vmware/vsphere-automation-sdk-python#210]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [ ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

- python version:

- vSphere version:

- Operating System/Shell (used to run SDK-based apps):

**Comment by anusha94** [comment]
@vishalxebia  Check your PYTHONPATH
Follow the instructions mentioned in https://github.com/vmware/vsphere-automation-sdk-python#first-set-pythonpath-to-use-sdk-helper-methods

If the error still persists, kindly provide your code snippet and environment details

**Comment by anusha94** [comment]
@vishalxebia 
Have you tried the above solution? Does the error still persist?

**Comment by vishalxebia** [comment]
@anusha94 The solution you suggested didn't solve but I upgraded my pip and setuptools, then installation using pip worked.

**Comment by anusha94** [comment]
Yes, that would be very necessary!
It is actually the [first step of the installation](https://github.com/vmware/vsphere-automation-sdk-python#installing-required-python-packages)

Glad it is working for you now. Closing this issue.

Thanks!
