### ISSUE TITLE
Error with your latest commit :  1e19006

### ISSUE THREAD

**Issue by HammerZ3it** [vmware/vsphere-automation-sdk-python#211]
Hi everyone,

I think there might be an issue with your latest commit : 1e19006
I git clone this repository to build and virtualenv on my pipeline and it seems that when I do : 

> pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file:///tmp/vsphere-automation-sdk-python/lib

There is an error directly linked to this commit : 

> Processing ./lib/vmc-draas-client-bindings/vmc_draas_client_bindings-1.4.0-py2.py3-none-any.whl

> --

> 15:24:25 |   | ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/vsphere-automation-sdk-python/lib/vmc-draas-client-bindings/vmc_draas_client_bindings-1.4.0-py2.py3-none-any.whl'

In fact there is nothing more than index.html in https://github.com/vmware/vsphere-automation-sdk-python/tree/master/lib/vmc-draas-client-bindings

It seems that this is an error but it can come from me somehow.

Regards,

**Comment by HammerZ3it** [comment]
This error made me improve our job and we are now cloning from tag instead of latest available version in git.
For those who wants to know how : 
`git clone --branch 7.0.0.0 https://github.com/vmware/vsphere-automation-sdk-python.git`

If you want to do it on a specifiq commit instead of tag (which I would recommend) : 
- Go on a the repo and get the commit id that you want : 
`git log`
Top is the latest commit

- Checkout on the git directory (on your server/pc)
`git checkout commithash`

**Comment by anusha94** [comment]
Thanks for reporting this, looking at it.

**Comment by anusha94** [comment]
The faulty commit has been reverted. Closing this issue.

Thanks.
