### ISSUE TITLE
how to set vm DiskProvisioningType

### ISSUE THREAD

**Issue by Jolin-blank** [vmware/vsphere-automation-sdk-python#212]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [ ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

- python version:

- vSphere version:

- Operating System/Shell (used to run SDK-based apps):

**Comment by anusha94** [comment]
Refer to the `DiskProvisioningType` documentation [here](https://vmware.github.io/vsphere-automation-sdk-python/vsphere/6.7.1/com.vmware.vcenter.html#com.vmware.vcenter.ovf_client.DiskProvisioningType)

If you find any issues, please provide output along with code snippet.

Thanks!

**Comment by Jolin-blank** [comment]
create vm default setting  is   thin ,but i wanna setting  is   eagerZeroedThick  , how can i  change it

**Comment by Jolin-blank** [comment]
> Refer to the `DiskProvisioningType` documentation [here](https://vmware.github.io/vsphere-automation-sdk-python/vsphere/6.7.1/com.vmware.vcenter.html#com.vmware.vcenter.ovf_client.DiskProvisioningType)
> 
> If you find any issues, please provide output along with code snippet.
> 
> Thanks!

create vm default setting is thin ,but i wanna setting is eagerZeroedThick , how can i change it

**Comment by anusha94** [comment]
Hi @Jolin-blank ,
Sorry  I missed your reply.
Currently from REST APIs, only while deploying from an OVF template, there is a way to set the DiskProvisioningType - see sample [here](https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/contentlibrary/ovfdeploy/deploy_ovf_template.py), you will have to set the [storage_provisioning value](https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/contentlibrary/ovfdeploy/deploy_ovf_template.py#L112) to a DiskProvisioningType instance as per the above documentation

But for any create vm operation, I think you can use pyvmomi (SOAP based APIs) to change the disk provisioning type once the create vm operation is complete
Check this [sample to get the disk_spec](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/add_disk_to_vm.py#L109)
And for `eagerZeroedThick`, the `backing type` will be `disk_spec.device.backing.eagerlyScrub = True`

**Comment by anusha94** [comment]
Closing this issue as a workaround is provided in the above comment. Feel free to open this issue if needed.

**Comment by Jolin-blank** [comment]
Thanks for you reply ，I will try it using pyvmomi.

| |
jolin_blank
|
|
邮箱：jolin_blank@163.com
|

Signature is customized by Netease Mail Master

On 04/21/2020 11:14, Anusha Hegde wrote:

Hi @Jolin-blank ,
Sorry I missed your reply.
Currently from REST APIs, only while deploying from an OVF template, there is a way to set the DiskProvisioningType - see sample here, you will have to set the storage_provisioning value to a DiskProvisioningType instance as per the above documentation

But for any create vm operation, I think you can use pyvmomi (SOAP based APIs) to change the disk provisioning type once the create vm operation is complete
Check this sample to get the disk_spec
And for eagerZeroedThick, the backing type will be disk_spec.device.backing.eagerlyScrub = True
