### ISSUE TITLE
How to get status progress of tasks (clone, deploy vm from template...)

### ISSUE THREAD

**Issue by dungla2011** [vmware/vsphere-automation-sdk-python#213]
Hello,
I use vcenter 6.7
I deploy, clone vm from template ... by API  ( ... rest/com/vmware/vcenter/ovf/library-item/id:<...>?~action=deploy)

It run well, and create vm done after some minute
But how can I get status of this task (percent complete, success , failed ...) with sdk, api
Thank you!

**Comment by anusha94** [comment]
Hi,
Please take a look at https://vmware.github.io/vsphere-automation-sdk-python/vsphere/6.7.1/com.vmware.cis.html#module-com.vmware.cis.task_client

**Comment by pushkargr** [comment]
Hi @anusha94 ,
If possible can you please share any sample or example to list, show info or show status of tasks for a VM using the above module. 
Thanks,
Pushkar

**Comment by anusha94** [comment]
Hi @pushkargr 
I checked and it seems that we can get the task progress/status only for those operations that return a task object containing the task_id.

For your use case, you can checkout [this sample](https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/contentlibrary/ovfdeploy/deploy_ovf_template.py)
The deploy method returns a [DeploymentResult](https://vmware.github.io/vsphere-automation-sdk-python/vsphere/7.0.0.1/com.vmware.vcenter.html?highlight=deploymentresult#com.vmware.vcenter.ovf_client.LibraryItem.DeploymentResult) object and you can check if the operation succeeded or not.

You can checkout other content-library related samples [here](https://github.com/vmware/vsphere-automation-sdk-python/tree/master/samples/vsphere/contentlibrary)

Thanks!

**Comment by anusha94** [comment]
Oh I just realized that deploy vm was related to @dungla2011 
@pushkargr 
Like I mentioned task progress can be tracked only for those operations that return a task object. You can refer to the [documentation](https://vmware.github.io/vsphere-automation-sdk-python/vsphere/7.0.0.1/) to know the return types of different APIs

**Comment by pushkargr** [comment]
Thanks @anusha94, Is there any other way to list the currently running tasks on a VM with status apart from this SDK then?

**Comment by anusha94** [comment]
Depends on what operations you are looking for. If they are older features like adding nic, serial ports, etc., you can consider using [pyvmomi](https://github.com/vmware/pyvmomi) (SOAP based APIs)
The vSphere Automation SDK is for REST APIs (available from VC 6.5+)

See some of the usage of task in pyvmomi in this [clone sample](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/clone_vm.py#L220) and [tasks utility](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/tools/tasks.py)

**Comment by anusha94** [comment]
Hi @pushkargr ,
So the UI uses SOAP APIs, in particular java bindings.
For Java, you can check out [vSphere Management SDK](https://code.vmware.com/web/sdk/7.0/vsphere-management)
For python, refer [pyvmomi](https://github.com/vmware/pyvmomi)

**Comment by anusha94** [comment]
Closing this issue as the Automation SDK currently supports tasks progress for a limited set of operations. Other SDK references are mentioned in the above comment.
