### ISSUE TITLE
AttributeError: 'StubFactory' object has no attribute '_invoke'

### ISSUE THREAD

**Issue by Jolin-blank** [vmware/vsphere-automation-sdk-python#214]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [ ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

- python version:

- vSphere version:

- Operating System/Shell (used to run SDK-based apps):

**Comment by anusha94** [comment]
@Jolin-blank have you upgraded to latest `pip` and `setuptools`?
use `pip install --upgrade pip setuptools`

**Comment by anusha94** [comment]
@Jolin-blank 
any update?

**Comment by anusha94** [comment]
closing this issue as there are no updates.
