### ISSUE TITLE
When can we get pinned version of vsphere-automation-sdk-python library?

### ISSUE THREAD

**Issue by vishalxebia** [vmware/vsphere-automation-sdk-python#216]
Since I am using this library as a requirement but we have pinned version dependency project, since it's a URL package dependency so can't use it in my project. Are you guys planning to upload to PyPI so we can use it as a specific version of this library?

**Comment by anusha94** [comment]
Hi @vishalxebia 

Here is a very long thread about pushing the package to PyPI #38 
Until then if you want to pin to a certain version, could you try this https://github.com/vmware/vsphere-automation-sdk-python/issues/211#issuecomment-593996001 way?

Thanks,
Anusha Hegde

**Comment by vishalxebia** [comment]
@anusha94  The thread didn't help much. I am not sure why you guys can't publish this SDK even people are requesting since 2 yrs almost.

**Comment by anusha94** [comment]
@vishalxebia 

Unfortunately, I don't have a definite answer to that right now. But we want to get there eventually.

In the meantime, try if this https://github.com/vmware/vsphere-automation-sdk-python/issues/211#issuecomment-593996001 works for you
You can pin to a release tag or commit.

**Comment by vishalxebia** [comment]
No that doesn't work either. In my project, we need to really pin the version like `vsphere-automation-sdk==1.23.0` something like this which can be installed easily by `pip`. But l have to find another way. Thanks @anusha94 .

**Comment by anusha94** [comment]
Closing this issue as pinning to a version is not supported as of now. Uploading to PyPI issue is being tracked separately.
