### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by UAnton** [vmware/vsphere-automation-sdk-python#220]
- [X] I am using the [latest SDK version]
- [X] This API is compatible with my vCenter version
- [X] I have searched [existing issues]

## Environment
- sdk package version: 
nsx-vmc-aws-integration-python-sdk     2.5.1.0.1.15419398
nsx-vmc-policy-python-sdk              2.5.1.0.1.15419398
pyobjc-framework-DictionaryServices    2.5.1
pyobjc-framework-EventKit              2.5.1
pyobjc-framework-FSEvents              2.5.1
pyobjc-framework-LaunchServices        2.5.1
pyobjc-framework-ScreenSaver           2.5.1
pyobjc-framework-ServiceManagement     2.5.1
pyobjc-framework-SyncServices          2.5.1
pyvmomi                                7.0
vapi-client-bindings                   3.3.0
vapi-common-client                     2.15.0
vapi-runtime                           2.15.0
vmc-client-bindings                    1.24.0
vmc-draas-client-bindings              1.5.0
vSphere-Automation-SDK                 1.25.0

- python version: Python 2.7.16

- vSphere version: 7.0

- Operating System/Shell (used to run SDK-based apps):
MacOS 10.15.4/zsh

## Steps or code snippet to reproduce

ansible-inventory --list -i .vmware.yaml

## Actual behavior
[WARNING]:  * Failed to parse /Users/az/.ansible/.vmware.yaml with vmware_vm_inventory plugin: Please install "PyVmomi" Python module as this is required for VMware Guest dynamic inventory plugin.
[WARNING]: Unable to parse /Users/az/.ansible/.vmware.yaml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available

**Comment by anusha94** [comment]
Hi @UAnton 
Can you describe what is the problem with Automation SDK here?
Or perhaps consider raising an issue on https://github.com/ansible-collections/vmware if it is Ansible issue.

**Comment by anusha94** [comment]
FYI: https://github.com/ansible-collections/vmware/blob/master/requirements.txt

**Comment by UAnton** [comment]
Thanks

**Comment by anusha94** [comment]
@UAnton 
https://github.com/ansible-collections/vmware/issues/154
This might be relevant to you.
