### ISSUE TITLE
Import Errors

### ISSUE THREAD

**Issue by rysevpd** [vmware/vsphere-automation-sdk-python#224]
- [ ] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)

- [ ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

- python version: 3.8

- vSphere version: 6.7

- Operating System/Shell (used to run SDK-based apps): Ubuntu 20.04, Peppermint 10. 

## Steps or code snippet to reproduce
Sorry, I don't speak English well.
Due to the fact that our company uses proxies, I can not download the SDK directly, so I downloaded it through the archive. When importing objects, it produces the following errors:

from vmware.vapi.vsphere.client import create_vsphere_client

from com.vmware.vcenter.vm.hardware_client import Cpu
from samples.vsphere.common.sample_util import parse_cli_args_vm
from samples.vsphere.common.sample_util import pp
from samples.vsphere.vcenter.setup import testbed

from samples.vsphere.vcenter.helper.vm_helper import get_vm
from samples.vsphere.common.ssl_helper import get_unverified_session

## Actual behavior
Traceback (most recent call last):
  File "/home/vminfo/PycharmProjects/VMware/con5.0.1.py", line 1, in <module>
    from vmware.vapi.vsphere.client import create_vsphere_client
  File "/home/vminfo/PycharmProjects/VMware/vmware/vapi/vsphere/client.py", line 10, in <module>
    from com.vmware.cis_client import Session
  File "/home/vminfo/PycharmProjects/VMware/com/vmware/cis_client.py", line 21, in <module>
    from vmware.vapi.bindings import type
ModuleNotFoundError: No module named 'vmware.vapi.bindings'
## Expected behavior
Process finished with exit code (0)

**Comment by anusha94** [comment]
@rysevpd 

Have you installed the SDK after downloading?

**Comment by rysevpd** [comment]
> @rysevpd
> 
> Вы установили SDK после загрузки?

Sorry, I'm new to Python. I downloaded the archive, unzipped it and added it to the project folder. Is this right or am I doing something wrong?

**Comment by anusha94** [comment]
You should install the SDK before using it.
If for some reason, you cannot perform the installation steps mentioned [here](https://github.com/vmware/vsphere-automation-sdk-python#installing-required-python-packages), I'd recommend you to try this -

```
$ cd vsphere-automation-sdk-python
$ pip install --upgrade -r requirements.txt --extra-index-url file:///<absolute_path_to_sdk>/lib
```

**Comment by rysevpd** [comment]
> pip install --upgrade -r requirements.txt --extra-index-url file:///<absolute_path_to_sdk>/lib

> bash: absolute_path_to_sdk: No such file or directory

**Comment by anusha94** [comment]
@rysevpd 

Replace absolute_path_to_sdk to the absolute path on your system where the SDK is unzipped.

**Comment by rysevpd** [comment]
Hooray! Everything is working! Thank you very much for your help and patience!
