### ISSUE TITLE
vsphere-automation-sdk-python and proxy error

### ISSUE THREAD

**Issue by rysevpd** [vmware/vsphere-automation-sdk-python#226]
- [ ] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [ ] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [ ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

- python version: 3.8

- vSphere version: 6.7

- Operating System/Shell (used to run SDK-based apps): Ubuntu 20.04

## Steps or code snippet to reproduce
**Good afternoon. Sorry, I don't speak English well... Our company uses proxy and it greatly interferes with my work. When I run the code which should just connect to vcenter and return the vms list.**
    
    `import requests
     import urllib3
     from vmware.vapi.vsphere.client import create_vsphere_client
     session = requests.session()
     session.verify = False
     urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
     vsphere_client = create_vsphere_client(server="*********", username="******",
                                             password="*****", session=session) 
     vsphere_client.vcenter.VM.list()`
**I will say right away that all the data for the connection is entered correctly. Theoretically, a proxy should not affect this. How can this be fixed? Thanks in advance to everyone.**
## Actual behavior

    `usr/bin/python3.8 /home/vminfo/PycharmProjects/VMware/tester.py
      Traceback (most recent call last): File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", 
      line 662, in urlopen self._prepare_proxy(conn)

    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 950, in _prepare_proxy 
    conn.connect()

    File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 308, in connect self._tunnel() File 
    "/usr/lib/python3.8/http/client.py", line 900, in _tunnel raise OSError("Tunnel connection failed: %d 
    %s" % (code, OSError: Tunnel connection failed: 504 Gateway Timeout During handling of the 
    above exception, another exception occurred:

    Traceback (most recent call last): File "/usr/lib/python3/dist-packages/requests/adapters.py", line 
    439, in send resp = conn.urlopen( File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", 
    line 719, in urlopen retries = retries.increment( File "/usr/lib/python3/dist- 
    packages/urllib3/util/retry.py", line 436, in increment raise MaxRetryError(_pool, url, error or 
    ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='********', 
    port=443): Max retries exceeded with url: /api (Caused by ProxyError('Cannot connect to proxy.', 
    OSError('Tunnel connection failed: 504 Gateway Timeout')))

    During handling of the above exception, another exception occurred: Traceback (most recent call 
    last): File "/home/vminfo/PycharmProjects/VMware/tester.py", line 15, in <module> vsphere_client 
    = create_vsphere_client(server='*******', username='********', password='*******', 
    session=session) File "/home/vminfo/.local/lib/python3.8/site - 
    packages/vmware/vapi/vsphere/client.py", line 170, in create_vsphere_client return 
    VsphereClient(session=session, server=server, username=username, File 
    "/home/vminfo/.local/lib/python3.8/site-packages/vmware/vapi/vsphere/client.py", line 113, in 
    __init__ session_id = session_svc.create() File "/home/vminfo/.local/lib/python3.8/site- 
    packages/com/vmware/cis_client.py", line 199, in create return self._invoke('create', None) File 
    "/home/vminfo/.local/lib/python3.8/site-packages/vmware/vapi/bindings/stub.py", line 345, in 
     _invoke return self._api_interface.native_invoke(ctx, _method_name, kwargs) File 
    "/home/vminfo/.local/lib/python3.8/site-packages/vmware/vapi/bindings/stub.py", line 266, in 
    native_invoke method_result = self.invoke(ctx, method_id, data_val) File 
    "/home/vminfo/.local/lib/python3.8/site-packages/vmware/vapi/bindings/stub.py", line 199, in 
    invoke return self._api_provider.invoke(self._iface_id.get_name(), File 
    "/home/vminfo/.local/lib/python3.8/site- 
    packages/vmware/vapi/security/client/security_context_filter.py", line 101, in invoke 
    method_result = ApiProviderFilter.invoke( File "/home/vminfo/.local/lib/python3.8/site- 
    packages/vmware/vapi/provider/filter.py", line 75, in invoke method_result = 
    self.next_provider.invoke( File "/home/vminfo/.local/lib/python3.8/site- 
    packages/vmware/vapi/protocol/client/msg/json_connector.py", line 79, in invoke response = 
    self._do_request(VAPI_INVOKE, ctx, params) File "/home/vminfo/.local/lib/python3.8/site- 
    packages/vmware/vapi/protocol/client/msg/json_connector.py", line 120, in _do_request 
    http_response = self.http_provider.do_request( File "/home/vminfo/.local/lib/python3.8/site- 
    packages/vmware/vapi/protocol/client/rpc/requests_provider.py", line 95, in do_request output = 
    self._session.request( File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in 
    request resp = self.send(prep, **send_kwargs) File "/usr/lib/python3/dist- 
    packages/requests/sessions.py", line 646, in send r = adapter.send(request, **kwargs) File 
    "/usr/lib/python3/dist-packages/requests/adapters.py", line 510, in send raise ProxyError(e, 
    request=request) requests.exceptions.ProxyError: HTTPSConnectionPool(host='*******', 
    port=443): Max retries exceeded with url: /api (Caused by ProxyError('Cannot connect to proxy.', 
    OSError('Tunnel connection failed: 504 Gateway Timeout'))) Exception ignored in: <function 
    VsphereClient.__del__ at 0x7efd9c9883a0> Traceback (most recent call last): File 
    "/home/vminfo/.local/lib/python3.8/site-packages/vmware/vapi/vsphere/client.py", line 138, in 
    __del__ if hasattr(self, 'session'): File "/home/vminfo/.local/lib/python3.8/site- 
    packages/vmware/vapi/bindings/stub.py", line 443, in __getattr__ return getattr(self._stub_factory, 
    name) File "/home/vminfo/.local/lib/python3.8/site-packages/vmware/vapi/bindings/stub.py", line 
    443, in __getattr__ return getattr(self._stub_factory, name) File 
    "/home/vminfo/.local/lib/python3.8/site-packages/vmware/vapi/bindings/stub.py", line 443, in 
    __getattr__ return getattr(self._stub_factory, name) [Previous line repeated 995 more times] 
    RecursionError: maximum recursion depth exceeded`

 
## Expected behavior

  **The program should list vms**

**Comment by anusha94** [comment]
@rysevpd 

As you can see from the error log
```
ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='********', 
port=443): Max retries exceeded with url: /api (Caused by ProxyError('Cannot connect to proxy.', 
OSError('Tunnel connection failed: 504 Gateway Timeout')))
```

The error is not from the SDK, in fact, the call is not coming through.
Do you have any setting to test this without proxy?

**Comment by anusha94** [comment]
@rysevpd 

Any update?

**Comment by anusha94** [comment]
Closing this PR due to inactivity. Feel free to reopen.

**Comment by oijkn** [comment]
For people who search the solution, you only need to add `session.trust_env = False`
