### ISSUE TITLE
cannot find relative information in doc

### ISSUE THREAD

**Issue by riveryc** [vmware/vsphere-automation-sdk-python#229]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

- python version:

- vSphere version: 6.7.0

- Operating System/Shell (used to run SDK-based apps): OSX

## Steps or code snippet to reproduce
Unable to find any documentation for `vmware.vapi.vsphere.client` on document page:
https://vmware.github.io/vsphere-automation-sdk-python/vsphere/6.7.0/

I want to know the list of the api and how to use them. However, there is nothing for this at all. 
I checked the the methods of `vsphere_client.vcenter.VM.`, but couldn't find anything useful in the doc. 

even for version 7.0, it's totally empty:
https://vmware.github.io/vsphere-automation-sdk-python/vsphere/7.0.0.1/vmware.vapi.vsphere.html (includes its sub-pages)

```bash
>>> vsphere_client.vcenter.VM.
vsphere_client.vcenter.VM.ClonePlacementSpec(         vsphere_client.vcenter.VM.RelocatePlacementSpec(
vsphere_client.vcenter.VM.CloneSpec(                  vsphere_client.vcenter.VM.RelocateSpec(
vsphere_client.vcenter.VM.ComputePlacementSpec(       vsphere_client.vcenter.VM.StoragePlacementSpec(
vsphere_client.vcenter.VM.CreateSpec(                 vsphere_client.vcenter.VM.StoragePolicySpec(
vsphere_client.vcenter.VM.DiskCloneSpec(              vsphere_client.vcenter.VM.Summary(
vsphere_client.vcenter.VM.DiskRelocateSpec(           vsphere_client.vcenter.VM.clone(
vsphere_client.vcenter.VM.FilterSpec(                 vsphere_client.vcenter.VM.clone_task(
vsphere_client.vcenter.VM.GuestCustomizationSpec(     vsphere_client.vcenter.VM.create(
vsphere_client.vcenter.VM.Info(                       vsphere_client.vcenter.VM.delete(
vsphere_client.vcenter.VM.InstantClonePlacementSpec(  vsphere_client.vcenter.VM.get(
vsphere_client.vcenter.VM.InstantCloneSpec(           vsphere_client.vcenter.VM.instant_clone(
vsphere_client.vcenter.VM.InventoryPlacementSpec(     vsphere_client.vcenter.VM.list(
vsphere_client.vcenter.VM.PlacementSpec(              vsphere_client.vcenter.VM.register(
vsphere_client.vcenter.VM.RESOURCE_TYPE               vsphere_client.vcenter.VM.relocate(
vsphere_client.vcenter.VM.RegisterPlacementSpec(      vsphere_client.vcenter.VM.relocate_task(
vsphere_client.vcenter.VM.RegisterSpec(               vsphere_client.vcenter.VM.unregister(
```

## Actual behavior
nothing in the doc
## Expected behavior
Full doc

**Comment by riveryc** [comment]
for example: I cannot find anything about "VM.clone()" at all... Any useful link to help?

Thanks!

**Comment by anusha94** [comment]
Check this out - https://vmware.github.io/vsphere-automation-sdk-python/vsphere/7.0.0.1/com.vmware.html#com.vmware.vcenter_client.VM

Refer to the method [clone_task](https://vmware.github.io/vsphere-automation-sdk-python/vsphere/7.0.0.1/com.vmware.html#com.vmware.vcenter_client.VM.clone_task) for clone operation.

Thanks for reporting the empty content, I'll get it fixed.

**Comment by anusha94** [comment]
Fixed empty content - https://vmware.github.io/vsphere-automation-sdk-python/vsphere/7.0.1.0/vmware.vapi.vsphere.html

Thanks!
