### ISSUE TITLE
can we use sdk to deploy a vm via vm templates stored in the folder?

### ISSUE THREAD

**Issue by suhasdombale123** [vmware/vsphere-automation-sdk-python#230]
In Vcenter UI we can deploy a vm using template......can the same be done via automation sdk???
the templates are in folder not in the Content library.

**Comment by anusha94** [comment]
@suhasdombale123 

I don't think that is possible. The REST API requires the template to be present in the content library. If you can move your templates to the content library, then you can use the SDK to deploy from there.
Here are few samples related to content library - https://github.com/vmware/vsphere-automation-sdk-python/tree/master/samples/vsphere/contentlibrary

Feel free to open this issue if you need more help. Thanks!
