### ISSUE TITLE
create_vsphere_client has no documentation

### ISSUE THREAD

**Issue by MrPippin66** [vmware/vsphere-automation-sdk-python#231]
- [x ] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [ x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [ x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 
vSphere-Automation-SDK             1.32.0

- python version:
Python 3.6.8

- vSphere version: 6.5

- Operating System/Shell (used to run SDK-based apps): Red Hat Enterprise Linux V7.8

I can find no documentation for the create_vsphere_client() function, specifically, the exception handlers and conditions.

I need to be able to write an exception block for it's use, and find no way to manage exceptions.

**Comment by anusha94** [comment]
Hi @MrPippin66 ,

Thanks for reporting this!
We will add the missing content for `vsphere_client` in the upcoming release. There is documentation on exception [here](https://vmware.github.io/vsphere-automation-sdk-python/vsphere/7.0.0.1/vmware.vapi.html?highlight=error#module-vmware.vapi.exception)

**Comment by anusha94** [comment]
`create_vsphere_client` documentation [here](https://vmware.github.io/vsphere-automation-sdk-python/vsphere/7.0.1.0/vmware.vapi.vsphere.html#vmware.vapi.vsphere.client.create_vsphere_client)
