### ISSUE TITLE
Broken NSX Documentation Links

### ISSUE THREAD

**Issue by anusha94** [vmware/vsphere-automation-sdk-python#237]
Recent update to NSX documentation introduced some broken links -

[NSX Manager APIs](https://vmware.github.io/vsphere-automation-sdk-python/nsx/nsx/index.html)
[NSX Policy](https://vmware.github.io/vsphere-automation-sdk-python/nsx/nsx_policy/index.html)
[NSX VMC Policy](https://vmware.github.io/vsphere-automation-sdk-python/nsx/nsx_vmc_policy/index.html)
[NSX VMC AWS Integration](https://vmware.github.io/vsphere-automation-sdk-python/nsx/nsx_vmc_policy/index.html)

Kindly update the same.

**Comment by ggoodvmw** [comment]
Fixed in https://github.com/vmware/vsphere-automation-sdk-python/pull/238
