### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement vapi-client-bindings==3.3.0vmc-client-bindings

### ISSUE THREAD

**Issue by vishnuvardhandvr** [vmware/vsphere-automation-sdk-python#241]
- [ ] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [ ] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [ ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

Package      Version
------------ -------
appdirs      1.4.4
cffi         1.14.3
cryptography 3.1.1
distlib      0.3.1
filelock     3.0.12
pip          20.2.3
pycparser    2.20
pyOpenSSL    16.2.0
setuptools   50.3.0
six          1.15.0
virtualenv   20.0.33
wheel        0.35.1

- python version:

3.8.5

- vSphere version: vSphere 6.5 U3

- Operating System/Shell (used to run SDK-based apps):
Windows 2008 R2

## Steps or code snippet to reproduce
Issue when running the command
python -m pip install -r requirements.txt

Output:
(venv) D:\vmware\vsphere-automation-sdk-python-master>python -m pip install -r requirements.txt
Ignoring suds: markers 'python_version < "3"' don't match your environment
Collecting lxml>=4.3.0
  Using cached lxml-4.5.2-cp38-cp38-win_amd64.whl (3.5 MB)
Collecting pyVmomi>=6.7
  Using cached pyvmomi-7.0.tar.gz (587 kB)
Collecting suds-jurko
  Using cached suds-jurko-0.6.tar.bz2 (143 kB)
ERROR: Could not find a version that satisfies the requirement vapi-client-bindings==3.3.0vmc-client-bindings (from -r requirements.txt (line 5)) (from versions: none)
ERROR: No matching distribution found for vapi-client-bindings==3.3.0vmc-client-bindings (from -r requirements.txt (line 5))

## Actual behavior

ERROR: Could not find a version that satisfies the requirement vapi-client-bindings==3.3.0vmc-client-bindings (from -r requirements.txt (line 5)) (from versions: none)
ERROR: No matching distribution found for vapi-client-bindings==3.3.0vmc-client-bindings (from -r requirements.txt (line 5))

**Comment by anusha94** [comment]
We have updated `vapi-client-bindings` to `3.5.0`,
Could you please try again?

**Comment by igorfraa** [comment]
@vishnuvardhandvr 

vsphere-automation-sdk-python installs not from PyPi, but from git: `pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git
`
or from local repo copy: 
```
cd vsphere-automation-sdk-python
pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file://$(pwd)/lib
```

**Comment by salimep** [comment]
@igorfraa 

even from git problem still exist , unable to install SDK for vmware

`pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git
Collecting git+https://github.com/vmware/vsphere-automation-sdk-python.git
  Cloning https://github.com/vmware/vsphere-automation-sdk-python.git to /private/var/folders/m9/9xcqjpjs16l2x50q_yv_bwxh0000gp/T/pip-9v7tg4ha-build


Collecting lxml>=4.3.0 (from vSphere-Automation-SDK==1.42.0)
  Using cached https://files.pythonhosted.org/packages/19/2f/a987692a0b2bfe11db25392c115c94e139efa8d78f1c987d2e51d4d2fa82/lxml-4.6.2-cp36-cp36m-macosx_10_9_x86_64.whl
Requirement already up-to-date: pyVmomi>=6.7 in ./Library/Python/3.6/lib/python/site-packages (from vSphere-Automation-SDK==1.42.0)
Collecting vapi-runtime@ file://localhost//private/var/folders/m9/9xcqjpjs16l2x50q_yv_bwxh0000gp/T/pip-9v7tg4ha-build/lib/vapi-runtime/vapi_runtime-2.19.0-py2.py3-none-any.whl (from vSphere-Automation-SDK==1.42.0)
  Could not find a version that satisfies the requirement vapi-runtime@ file://localhost//private/var/folders/m9/9xcqjpjs16l2x50q_yv_bwxh0000gp/T/pip-9v7tg4ha-build/lib/vapi-runtime/vapi_runtime-2.19.0-py2.py3-none-any.whl (from vSphere-Automation-SDK==1.42.0) (from versions: )
No matching distribution found for vapi-runtime@ file://localhost//private/var/folders/m9/9xcqjpjs16l2x50q_yv_bwxh0000gp/T/pip-9v7tg4ha-build/lib/vapi-runtime/vapi_runtime-2.19.0-py2.py3-none-any.whl (from vSphere-Automation-SDK==1.42.0)
You are using pip version 9.0.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

**Comment by salimep** [comment]
issue has been resolved 
```

`pip install --upgrade pip setuptools
pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git`
```
