### ISSUE TITLE
Could not find a version that satisfies the requirement vsphere-automation-sdk-python>=1.0 (from test-pkg==0.0.1) (from versions: )

### ISSUE THREAD

**Issue by prm-svm-17** [vmware/vsphere-automation-sdk-python#243]
Have tried installed vsphere-automation-sdk-python through setuptools.setup(), but facing the below error,

Collecting vsphere-automation-sdk-python>=1.0 (from test-pkg==0.0.1)
  Could not find a version that satisfies the requirement vsphere-automation-sdk-python>=1.0 (from test-pkg==0.0.1) (from versions: )
No matching distribution found for vsphere-automation-sdk-python>=1.0 (from test-pkg==0.0.1)

install_reqs = ["vsphere-automation-sdk-python==7.0.0.0"]

setuptools.setup(
    name="test-pkg",
    install_requires=install_reqs,
    dependency_links=['git+git://github.com/vmware/vsphere-automation-sdk-python.git#egg=vsphere-automation-sdk-python'],
    ...., )

pip version 9.0.3
python - 3.6

**Comment by anusha94** [comment]
@prm-svm-17 

Are you trying to install the SDK itself?
Please follow these steps -
- [installing required packages](https://github.com/vmware/vsphere-automation-sdk-python/#installing-required-python-packages)
- [set PYTHONPATH](https://github.com/vmware/vsphere-automation-sdk-python/#first-set-pythonpath-to-use-sdk-helper-methods)

If not, can you please describe your requirement?

**Comment by prm-svm-17** [comment]
Thanks @anusha94 for reply,

SDK Installation through PIP is working fine though. Below is our requirement,

Creating a wheel package of our automation libraries, which in turn referring vSphere Automation SDKs. So while trying to package our libraries including vSphere Automation SDK through setuptools.setup(), we are encountering below issue.

(pip_env_1) -bash-4.2$ pip install test-pkg-0.0.1-py3-none-any.whl
Processing ./test-pkg-0.0.1-py3-none-any.whl
Collecting vsphere-automation-sdk-python@ git+https://github.com/vmware/vsphere-automation-sdk-python.git
  Cloning https://github.com/vmware/vsphere-automation-sdk-python.git to /tmp/pip-install-qp7hm6tu/vsphere-automation-sdk-python
  WARNING: Generating metadata for package vsphere-automation-sdk-python produced metadata for project name vsphere-automation-sdk. Fix your #egg=vsphere-automation-sdk-python fragments.
ERROR: Exception:
Traceback (most recent call last):
  File "..../pip_env_1/lib64/python3.6/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "..../pip_env_1/lib64/python3.6/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "..../pip_env_1/lib64/python3.6/site-packages/pip/_internal/commands/install.py", line 324, in run
    reqs, check_supported_wheels=not options.target_dir
  File "..../pip_env_1/lib64/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "..../pip_env_1/lib64/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 425, in _resolve_one
    assert req_to_install.user_supplied

**Comment by anusha94** [comment]
Hi @prm-svm-17 ,

The following worked for me -
`install_reqs = ["vSphere-Automation-SDK @ git+git://github.com/vmware/vsphere-automation-sdk-python@v7.0.1.0#egg=vsphere-automation-sdk-python"]`

You can remove the entry for the SDK from `dependency_links`

Let me know if it works for you.

**Comment by prm-svm-17** [comment]
Hi @anusha94,

We are getting the below error after adding the install_reqs in our setup.py

> (pip_env_1) -bash-4.2$ pip install dist/test-pkg-0.0.1-py3-none-any.whl --no-cache-dir
Processing ./dist/test-pkg-0.0.1-py3-none-any.whl
Collecting dumper
  Downloading Dumper-1.2.0-py2.py3-none-any.whl (13 kB)
Collecting vSphere-Automation-SDK@ git+git://github.com/vmware/vsphere-automation-sdk-python@v7.0.1.0#egg=vsphere-automation-sdk-python
  Cloning git://github.com/vmware/vsphere-automation-sdk-python (to revision v7.0.1.0) to /tmp/pip-install-b8d2xba2/vsphere-automation-sdk
ERROR: Command errored out with exit status 128: git clone -q git://github.com/vmware/vsphere-automation-sdk-python /tmp/pip-install-b8d2xba2/vsphere-automation-sdk Check the logs for full command output.
(pip_env_1) -bash-4.2$ pip --version
pip 20.2.4 from .../pip_env_1/lib64/python3.6/site-packages/pip (python 3.6)

**setup.py:**
install_reqs = ["dumper", "vSphere-Automation-SDK @ git+git://github.com/vmware/vsphere-automation-sdk-python@v7.0.1.0#egg=vsphere-automation-sdk-python"]
setuptools.setup(
    name="test-pkg",
    install_requires=install_reqs,
    version="0.0.1",
    packages=setuptools.find_packages(),
    include_package_data=True,
    python_requires='>=3.6',
)

**Comment by anusha94** [comment]
@prm-svm-17 

Were you able to resolve this?

**Comment by prm-svm-17** [comment]
@anusha94 - yes, the issue is resolved.
Closing this ticket

**Comment by prm-svm-17** [comment]
Thanks for your help
