### ISSUE TITLE
Cannot use the repo with poetry unless it's pulled locally. 

### ISSUE THREAD

**Issue by tyao117** [vmware/vsphere-automation-sdk-python#255]
- [X] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [X] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [X] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

I just have a feature request or enhancement. Can the `setup.py` be changed that it does not need to depend on a local file to be installed? 
(example of the problem): https://github.com/vmware/vsphere-automation-sdk-python/blob/7c4a420da3a8fabe47ec80098a4ea6a1991272da/setup.py#L18
I can't use it with poetry unless I pull the repo locally, and I'm trying to explore the possibility of putting this repo as a dependency without needing to copy it using poetry. 
Here a link to the issue I was having:
https://github.com/python-poetry/poetry/issues/3481
specifically:
https://github.com/python-poetry/poetry/issues/3481#issuecomment-743800678

**Comment by anusha94** [comment]
Hi @tyao117 

The `.whl` files are present in `lib/`, so I don't see another way to install it - unless the repo is pushed to PyPI, and that is a work in progress.

**Comment by tyao117** [comment]
hey @anusha94; thanks for responding, when is this going to be pushed to PyPI, and is there a way to reference the `.whl` using the github url rather than the local path?

**Comment by anusha94** [comment]
@tyao117 

Are you looking for something like this?
https://github.com/vmware/vsphere-automation-sdk-python/pull/258/files

**Comment by anusha94** [comment]
Closing this PR due to inactivity, feel free to reopen.

**Comment by dcedcha** [comment]
I'm also facing this issue when using poetry (instead of pip) to manage requirements in my project

**Comment by tyao117** [comment]
@dcedcha, until the lib packages are uploaded to pypi, poetry wouldn't be able to support unless you manually clone the repo and have the `.toml` file of peotry refer to it as a local file.
