### ISSUE TITLE
List VMs IPs

### ISSUE THREAD

**Issue by Elinoy-1** [vmware/vsphere-automation-sdk-python#260]
Hi,

I'd like to retrieve a list of all our virtual machines - names and IPs.
According to what I found, I can use the following option to retrieve all virtual machines:
```
vsphere_client.vcenter.VM.list()
[Summary(vm='vm-58', name='standalone-20e4bd3af-esx.0-vm.0', power_state=State(string='POWERED_OFF'), cpu_count=1, memory_size_mib=256), 
```
However, the output doesn't include the IPs. What am I missing here? is there an option to include it?

Thank you!

**Comment by mike-19** [comment]
You can retrieve the IP-address of the VM using the below 
`
 ip = vsphere_client.vcenter.vm.guest.Identity.get(vm='vm-58')
 ip.ip_address
`
