### ISSUE TITLE
InternalServerError from vcenter.VM.get: invalid UnionCase state

### ISSUE THREAD

**Issue by optiz0r** [vmware/vsphere-automation-sdk-python#267]
- [/] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [/] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [/] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

```
nsx-vmc-aws-integration-python-sdk 2.5.1.0.1.15419398
nsx-vmc-policy-python-sdk          2.5.1.0.1.15419398
pyvmomi                            7.0.1             
vapi-client-bindings               3.2.0             
vapi-common-client                 2.14.0            
vapi-runtime                       2.14.0            
vmc-client-bindings                1.24.0            
vmc-draas-client-bindings          1.4.0             
vSphere-Automation-SDK             1.51.0            
```

- python version:

```
Python 3.6.8
```

- vSphere version:

```
7.0.1.17491160
```

- Operating System/Shell (used to run SDK-based apps):

```
CentOS Linux release 8.3.2011
GNU bash, version 4.4.19(1)-release (x86_64-redhat-linux-gnu)
```

## Steps or code snippet to reproduce

```
import requests
import urllib3
from pprint import pprint
from vmware.vapi.vsphere.client import create_vsphere_client
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

session = requests.session()
session.verify = False
vs = create_vsphere_client(
    server='vsphere.example.com',
    username='username',
    password='password',
    session=session)
vm = vs.vcenter.VM.get('vm-1861')
pprint(vm)
```

## Actual behavior

For approx 4% of VMs managed by the vcenter, the following exception is raised when fetching the VM metadata.

```
Traceback (most recent call last):
  File "/home/me/git/test/test.py", line 24, in <module>
    main()
  File "/home/me/git/test/test.py", line 20, in main
    vs.vcenter.VM.get('vm-1861')
  File "/home/me/.virtualenvs/test/lib64/python3.6/site-packages/com/vmware/vcenter_client.py", line 5079, in get
    'vm': vm,
  File "/home/me/.virtualenvs/test/lib64/python3.6/site-packages/vmware/vapi/bindings/stub.py", line 345, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/home/me/.virtualenvs/test/lib64/python3.6/site-packages/vmware/vapi/bindings/stub.py", line 298, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.InternalServerError: {messages : [LocalizableMessage(id='vapi.invoke.invalid.output', default_message='Invalid output for method: get', args=['get'], params=None, localized=None), LocalizableMessage(id='vapi.data.union.invalid.case.state', default_message="Invalid UnionCase state. Expected 'set' got: 'not-set' for 'type'", args=["'set'", "'not-set'", 'type'], params=None, localized=None)], data : None, error_type : None}
```

All affected machines are running Linux, but a range of different OSes both installed and as the configured VM OS - Fedora, Centos 7, CentOS 8, SUSE 12. The affected VMs are spread across different VMware clusters, hosts, and have a range of compatibility levels from 14 to 17.

## Expected behavior

VM metadata to be printed out successfully, which works for the other 96% of VMs managed by the vcenter.

**Comment by yanglijian201** [comment]
It also happens in my local setup when there is a vm which is not accessible.

**Comment by optiz0r** [comment]
Just to add some feedback on this (not intending to reopen the issue here), vmware support have confirmed there is an open problem in vcenter where it returns back errors instead of vm metadata for some VMs. Temporary workaround is to live migrate, or rename the VM. Support haven't given me the PR number to leave here for reference.

**Comment by yanglijian201** [comment]
> Just to add some feedback on this (not intending to reopen the issue here), vmware support have confirmed there is an open problem in vcenter where it returns back errors instead of vm metadata for some VMs. Temporary workaround is to live migrate, or rename the VM. Support haven't given me the PR number to leave here for reference.

This issue has been there for a long time, really have no idea what vmware teams are doing. Just tell us fix or not. If fix, what's the PR...

**Comment by optiz0r** [comment]
https://kb.vmware.com/s/article/85053
