### ISSUE TITLE
[Errno 2] No such file or directory: '//tmp/pip-req-build-ixsiy671/lib/vapi-runtime/vapi_runtime-2.19.0-py2.py3-none-any.whl'

### ISSUE THREAD

**Issue by matthewit2** [vmware/vsphere-automation-sdk-python#271]
I am using the latest SDK version and I'm unable to get it to install using the documented method on this page. I have tried creating a new venv for python 3 and still get the error listed below

## Environment
- sdk package version: 
Does not install

- python version:
Python 3.6.8

- vSphere version:
7.0 U2

- Operating System/Shell (used to run SDK-based apps):
RHEL 8

## Steps or code snippet to reproduce
pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git

## Actual behavior
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '//tmp/pip-req-build-ixsiy671/lib/vapi-runtime/vapi_runtime-2.19.0-py2.py3-none-any.whl'

## Expected behavior
sdk installs

**Comment by matthewit2** [comment]
Digging into the folder structure shows that there is a new vapi runtime file /tmp/vsphere-automation-sdk-python/lib/vapi-runtime/vapi_runtime-2.25.0-py2.py3-none-any.whl

**Comment by sumitAgrawal007** [comment]
Thanks for reporting, fixed the version.

**Comment by Halkcyon** [comment]
@sumitAgrawal007 attempting to install from a git link or tarball at the latest tag/release still results in the same error.

```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\\\Users\\[redacted]\\AppData\\Local\\Temp\\pip-req-build-qy6fukll\\lib\\vapi-runtime\\vapi_runtime-2.19.0-py2.py3-none-any.whl'
```

I tried both:

* `https://github.com/vmware/vsphere-automation-sdk-python/archive/refs/tags/v7.0.2.00100.tar.gz`
* `git+https://github.com/vmware/vsphere-automation-sdk-python.git@v7.0.2.00100`

For now, I'm leaving my requirements file `@master`, but I'd appreciate being able to pin a version to avoid breaks in the future.

**Comment by shwetapurohit** [comment]
@Halkcyon : Fixed the issue.
