### ISSUE TITLE
Source repository?

### ISSUE THREAD

**Issue by evilensky** [vmware/vsphere-automation-sdk-python#274]
The [VMware site](https://code.vmware.com/web/sdk/7.0/vsphere-automation-python) says:

>Please note, the vSphere Automation SDK for Python is now available as an Open Source SDK and can be contributed to or downloaded from Github here.

With a link to this repository.

I have not checked every folder, but this repository appears to wheels and documentation.

Is there a source repository that can be contributed to or code explored?

**Comment by shwetapurohit** [comment]
@evilensky  
You can contribute samples not the wheels. 
Install SDK in a Python virtual environment is highly recommended.
