### ISSUE TITLE
Unable to get cluster in namespace_management

### ISSUE THREAD

**Issue by zhonghankong** [vmware/vsphere-automation-sdk-python#281]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 
nsx-vmc-aws-integration-python-sdk 3.0.3.0.0.17723277
nsx-vmc-policy-python-sdk          3.0.3.0.0.17723277
pyvmomi                            7.0.1
semantic-version                   2.8.5
vapi-client-bindings               3.6.0
vapi-common-client                 2.25.0
vapi-runtime                       2.25.0
vmc-client-bindings                1.40.0
vmc-draas-client-bindings          1.17.0
vSphere-Automation-SDK             1.62.0

- python version: Python 3.6.12

- vSphere version: v7.0.2.00200

- Operating System/Shell (used to run SDK-based apps): RHEL 7

## Steps or code snippet to reproduce
Trying to pull com.vmware.vcenter.namespace_management.software_client.Cluster info to get Kubenetes status/status_message on a Tanzu with Vsphere cluster. 

I am able to pull the required info via PowerCLI and through the API on vCenter Developer Center

However namespace_management is not available via vSphere-Automation-SDK-Python, i think. 

Referring to https://vmware.github.io/vsphere-automation-sdk-python/vsphere/7.0.2.0/com.vmware.vcenter.namespace_management.html#module-com.vmware.vcenter.namespace_management.stats_client, it should be available. 

## Actual behavior
```
>>> from pprint import pprint
>>> import requests
>>> from vmware.vapi.vsphere.client import create_vsphere_client
>>>
>>> session = requests.session()
>>> session.verify = False
>>> requests.packages.urllib3.disable_warnings()
>>>
>>> client = create_vsphere_client(server='xxxxxx', username='xxx@xxx', password='xxx', session=session)
>>> clusters = client.vcenter.namespace_management.software_client.Clusters.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vpcadm6/runesx/venv-runesx/lib64/python3.6/site-packages/vmware/vapi/bindings/stub.py", line 413, in __getattribute__
    result = object.__getattribute__(self, name)
AttributeError: 'StubFactory' object has no attribute 'namespace_management'
>>>
>>> client.vcenter.__dir__()
['_stub_config', 'Cluster', 'Datacenter', 'Datastore', 'Folder', 'Host', 'Network', 'ResourcePool', 'VM', 'Deployment', 'certificate_management', 'crypto_manager', 'datastore', 'deployment', 'guest', 'identity', 'services', 'storage', 'system_config', 'tagging', 'topology', 'trusted_infrastructure', 'vcha', 'vm', 'hvc', 'compute', 'inventory', 'iso', 'ovf', 'vm_template', 'lcm', '__module__', '_attrs', '__doc__', '__init__', '__getattribute__', '__dict__', '__weakref__', '__repr__', '__hash__', '__str__', '__setattr__', '__delattr__', '__lt__', '__le__', '__eq__', '__ne__', '__gt__', '__ge__', '__new__', '__reduce_ex__', '__reduce__', '__subclasshook__', '__init_subclass__', '__format__', '__sizeof__', '__dir__', '__class__']
```
## Expected behavior
namespace_management should be available

**Comment by shwetapurohit** [comment]
@zhonghankong 
Please take look at the sample below:
https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/vcenter/namespace_management/list_clusters.py

 This works and the o/p of the sample is 
`(venv) spurohit@spurohit-a01 vsphere-automation-sdk-python % python samples/vsphere/vcenter/vm/test.py  -s 10.x.x.x -u un -p pwd  -v
vcenter server = 10.x.x.x
vc username = Administrator@vsphere.local
Session ID :  2bba9a789989d20ed9cfafa30a16b9d7
----------------------------
List Of clusters
----------------------------
[Summary(cluster='domain-c8', cluster_name='wcpe2e-compute-cluster', stats=Stats(cpu_used=0, cpu_capacity=0, memory_used=0, memory_capacity=0, storage_used=0, storage_capacity=0), config_status=ConfigStatus(string='RUNNING'), kubernetes_status=KubernetesStatus(string='READY'))]
`
Let me know if you are still facing any issues.

Thanks
