### ISSUE TITLE
ERROR: No matching distribution found for suds-jurko

### ISSUE THREAD

**Issue by smallfish01** [vmware/vsphere-automation-sdk-python#285]
## Environment
- sdk package version: 

PS C:\Windows\system32> pip list
Package            Version
------------------ ---------
certifi            2021.5.30
charset-normalizer 2.0.4
idna               3.2
lxml               4.6.3
pip                21.2.4
pyvmomi            7.0.2
requests           2.26.0
setuptools         58.0.4
six                1.16.0
suds               0.3.5
suds-py3           1.4.4.1
urllib3            1.26.6
wheel              0.37.0

- python version:3.9.7

- vSphere version:6.7
- Operating System/Shell (used to run SDK-based apps):
Windows 10

When I install Required Python Packages and meet the error:

PS D:\py-study> pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git
Collecting git+https://github.com/vmware/vsphere-automation-sdk-python.git
  Cloning https://github.com/vmware/vsphere-automation-sdk-python.git to c:\users\admin\appdata\local\temp\pip-req-build-rmiabocc
  Running command git clone -q https://github.com/vmware/vsphere-automation-sdk-python.git 'C:\Users\admin\AppData\Local\Temp\pip-req-build-rmiabocc'
  Resolved https://github.com/vmware/vsphere-automation-sdk-python.git to commit bfbfd4d7e9b58d73ba1cf5197014740e69a32709
Processing c:\users\admin\appdata\local\temp\pip-req-build-rmiabocc\lib\vapi-runtime\vapi_runtime-2.25.0-py2.py3-none-any.whl
Processing c:\users\admin\appdata\local\temp\pip-req-build-rmiabocc\lib\vapi-client-bindings\vapi_client_bindings-3.6.0-py2.py3-none-any.whl
Processing c:\users\admin\appdata\local\temp\pip-req-build-rmiabocc\lib\vapi-common-client\vapi_common_client-2.25.0-py2.py3-none-any.whl
Processing c:\users\admin\appdata\local\temp\pip-req-build-rmiabocc\lib\vmc-client-bindings\vmc_client_bindings-1.52.0-py2.py3-none-any.whl
Processing c:\users\admin\appdata\local\temp\pip-req-build-rmiabocc\lib\nsx-python-sdk\nsx_python_sdk-3.1.2.1.1-py2.py3-none-any.whl
Processing c:\users\admin\appdata\local\temp\pip-req-build-rmiabocc\lib\nsx-policy-python-sdk\nsx_policy_python_sdk-3.1.2.1.1-py2.py3-none-any.whl
Processing c:\users\admin\appdata\local\temp\pip-req-build-rmiabocc\lib\nsx-vmc-policy-python-sdk\nsx_vmc_policy_python_sdk-3.1.2.1.1-py2.py3-none-any.whl
Processing c:\users\admin\appdata\local\temp\pip-req-build-rmiabocc\lib\nsx-vmc-aws-integration-python-sdk\nsx_vmc_aws_integration_python_sdk-3.1.2.1.1-py2.py3-none-any.whl
Processing c:\users\admin\appdata\local\temp\pip-req-build-rmiabocc\lib\vmc-draas-client-bindings\vmc_draas_client_bindings-1.18.0-py2.py3-none-any.whl
Collecting lxml>=4.3.0
  Using cached lxml-4.6.3-cp39-cp39-win_amd64.whl (3.5 MB)
Collecting pyVmomi>=6.7
  Using cached pyvmomi-7.0.2.tar.gz (589 kB)
Collecting suds-jurko
  Using cached suds-jurko-0.6.zip (255 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\admin\AppData\Local\Programs\Python\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-z5_r6go5\\suds-jurko_b3f78ddce3c14dde8db5f9f103caa099\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-z5_r6go5\\suds-jurko_b3f78ddce3c14dde8db5f9f103caa099\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\admin\AppData\Local\Temp\pip-pip-egg-info-dkuna2z_'
         cwd: C:\Users\admin\AppData\Local\Temp\pip-install-z5_r6go5\suds-jurko_b3f78ddce3c14dde8db5f9f103caa099\
    Complete output (1 lines):
   ###  error in suds-jurko setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d0/88/f3bed9b494e0dae26bd55e5f3d527b8244208125024727267e8109956a11/suds-jurko-0.6.zip#sha256=1cb7252cb13018fc32887c3a834ed7c6648a5b5c4c159be5806da2e1785399e8 (from https://pypi.org/simple/suds-jurko/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached suds-jurko-0.6.tar.bz2 (143 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\admin\AppData\Local\Programs\Python\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-z5_r6go5\\suds-jurko_b3461d80d54442e1b68cba8961c98d53\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-z5_r6go5\\suds-jurko_b3461d80d54442e1b68cba8961c98d53\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\admin\AppData\Local\Temp\pip-pip-egg-info-mw15i4o1'
         cwd: C:\Users\admin\AppData\Local\Temp\pip-install-z5_r6go5\suds-jurko_b3461d80d54442e1b68cba8961c98d53\
    Complete output (1 lines):
 ###    error in suds-jurko setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bd/6f/54fbf0999a606680d27c69b1ad12dfff62768ecb9fe48524cebda6eb4423/suds-jurko-0.6.tar.bz2#sha256=29edb72fd21e3044093d86f33c66cf847c5aaab26d64cb90e69e528ef014e57f (from https://pypi.org/simple/suds-jurko/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached suds-jurko-0.5.zip (220 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\admin\AppData\Local\Programs\Python\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-z5_r6go5\\suds-jurko_d496e2ca57f94f04ab98c9bec38fc3c6\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-z5_r6go5\\suds-jurko_d496e2ca57f94f04ab98c9bec38fc3c6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\admin\AppData\Local\Temp\pip-pip-egg-info-06srq7fy'
         cwd: C:\Users\admin\AppData\Local\Temp\pip-install-z5_r6go5\suds-jurko_d496e2ca57f94f04ab98c9bec38fc3c6\
    Complete output (1 lines):
   ###  error in suds-jurko setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/72/22/13c6ff1e731880523ceb7d6137b9450f7cca5b4bee8411017bad23af226c/suds-jurko-0.5.zip#sha256=7ba3267d53b4d5f87a26a4c01efaa01ad85ae620462f0cd72e49d1c340925261 (from https://pypi.org/simple/suds-jurko/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached suds-jurko-0.5.tar.bz2 (122 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\admin\AppData\Local\Programs\Python\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-z5_r6go5\\suds-jurko_e30d75e5fdaf4cb587b6ea23255735d8\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-z5_r6go5\\suds-jurko_e30d75e5fdaf4cb587b6ea23255735d8\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\admin\AppData\Local\Temp\pip-pip-egg-info-krgo0bn2'
         cwd: C:\Users\admin\AppData\Local\Temp\pip-install-z5_r6go5\suds-jurko_e30d75e5fdaf4cb587b6ea23255735d8\
    Complete output (1 lines):
    **error in suds-jurko setup command: use_2to3 is invalid.**
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/40/cc/2fad53352898ebfef8b11e4b6b0ef0fac0ee8162c735db28c558d511039c/suds-jurko-0.5.tar.bz2#sha256=3dd119ced5335d71a2844e380e6a509a1f05e6f5bbb5d1f8a2fdf5c74adff8ed (from https://pypi.org/simple/suds-jurko/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement suds-jurko (from vsphere-automation-sdk) (from versions: 0.4.1.jurko.1, 0.4.1.jurko.2, 0.4.1.jurko.3, 0.4.1.jurko.4, 0.4.1.jurko.5, 0.5, 0.6)
**ERROR: No matching distribution found for suds-jurko**

**Comment by thomsmoreau** [comment]
I made it work in my Dockerfile by doing so:
RUN pip install suds-jurko
RUN pip install --upgrade --no-cache-dir pip setuptools 
RUN pip install --upgrade --no-cache-dir git+https://github.com/vmware/vsphere-automation-sdk-python.git 

It seems to avoid the issue with the "No matching distribution found for suds-jurko" and setup completes without any issue

**Comment by smallfish01** [comment]
> I made it work in my Dockerfile by doing so:
> RUN pip install suds-jurko
> RUN pip install --upgrade --no-cache-dir pip setuptools
> RUN pip install --upgrade --no-cache-dir git+https://github.com/vmware/vsphere-automation-sdk-python.git
> 
> It seems to avoid the issue with the "No matching distribution found for suds-jurko" and setup completes without any issue

Hi Thomsmoreau,

Thanks for you replied.

I did many test today and I found when I using pip9 install suds-jurko is ok.

# pip3.9 list
Package    Version
---------- -------
pip        21.2.4
setuptools 57.4.0
suds-jurko 0.6

But when I tried running: pip3.9 install -r requirements.txt and got error:

]# pip3.9 install -r requirements.txt
Ignoring suds: markers 'python_version < "3"' don't match your environment
Collecting lxml>=4.3.0
  Using cached lxml-4.6.3-cp39-cp39-manylinux2014_x86_64.whl (6.9 MB)
Collecting pyVmomi>=6.7
  Using cached pyvmomi-7.0.2.tar.gz (589 kB)
Requirement already satisfied: suds-jurko in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.6)
ERROR: Could not find a version that satisfies the requirement vapi-client-bindings==3.6.0 (from versions: none)
ERROR: No matching distribution found for vapi-client-bindings==3.6.0

So I am tring install again:
pip3.9  install --upgrade --no-cache-dir git+https://github.com/vmware/vsphere-automation-sdk-python.git

Now looks ok:
(isoenv) [root@localhost vsphere-automation-sdk-python]# pip3.9 list
Package                            Version
---------------------------------- ---------
certifi                            2021.5.30
cffi                               1.14.6
charset-normalizer                 2.0.4
cryptography                       3.4.8
idna                               3.2
lxml                               4.6.3
nsx-policy-python-sdk              3.1.2.1.1
nsx-python-sdk                     3.1.2.1.1
nsx-vmc-aws-integration-python-sdk 3.1.2.1.1
nsx-vmc-policy-python-sdk          3.1.2.1.1
pip                                21.2.4
pycparser                          2.20
pyOpenSSL                          20.0.1
pyvmomi                            7.0.2
requests                           2.26.0
setuptools                         58.0.4
six                                1.16.0
suds-jurko                         0.6
urllib3                            1.26.6
vapi-client-bindings               3.6.0
vapi-common-client                 2.25.0
vapi-runtime                       2.25.0
vmc-client-bindings                1.52.0
vmc-draas-client-bindings          1.18.0
vSphere-Automation-SDK             1.69.0
wheel                              0.37.0


Thank you so much.

**Comment by smallfish01** [comment]
It works now when I reinstall suds-jurko using pip3.9.

**Comment by snvad** [comment]
Can you help me, please.
New venv with updated setuptools and pip. A similar error occurs.

```
$ python3 -m venv venv
$ . ./venv/bin/activate
(venv)$ python3 --version
Python 3.9.2
(venv)$ pip3 freeze
pkg-resources==0.0.0
(venv)$ pip3 install --upgrade --no-cache-dir setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/c4/c1/aed7dfedb18ea73d7713bf6ca034ab001a6425be49ffa7e79bbd5999f677/setuptools-58.0.4-py3-none-any.whl (816kB)
    100% |████████████████████████████████| 819kB 4.1MB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 40.8.0
    Uninstalling setuptools-40.8.0:
      Successfully uninstalled setuptools-40.8.0
Successfully installed setuptools-58.0.4
(venv)$ pip3 install --upgrade --no-cache-dir pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/ca/31/b88ef447d595963c01060998cb329251648acf4a067721b0452c45527eb8/pip-21.2.4-py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 19.2MB/s
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-21.2.4
(venv)$ pip3 install --upgrade --no-cache-dir git+https://github.com/vmware/vsphere-automation-sdk-python.git
... some info ...
Collecting suds-jurko
  Downloading suds-jurko-0.6.zip (255 kB)
     |████████████████████████████████| 255 kB 24.4 MB/s
    ERROR: Command errored out with exit status 1:
     command: /tmp/test/venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ncn2hg6a/suds-jurko_021f78676c884e4ebdd29980f70899b0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ncn2hg6a/suds-jurko_021f78676c884e4ebdd29980f70899b0/setup.py'"'"';f = getattr(tokenize, '"'
"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'
"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-hhvwumoc
         cwd: /tmp/pip-install-ncn2hg6a/suds-jurko_021f78676c884e4ebdd29980f70899b0/
    Complete output (1 lines):
    error in suds-jurko setup command: use_2to3 is invalid.
---------------------------------------- 
... some other info ...
ERROR: Could not find a version that satisfies the requirement suds-jurko (from vsphere-automation-sdk) (from versions: 0.4.1.jurko.1, 0.4.1.jurko.2, 0.4.1.jurko.3, 0.4.1.jurko.4, 0.4.1.jurko.5, 0.5, 0.6)
ERROR: No matching distribution found for suds-jurko
```

**Comment by MatMatMatMatMatMat** [comment]
Hello,
setuptools >58.0.1 break the support of use_2to3 changes here : https://github.com/pypa/setuptools/blob/main/CHANGES.rst
vsphere-automation-sdk-python has suds-jurko in his requirements, but this package is stalled (last version in 2014)

Quick fix : use setuptools < 58.0.2

Permanent fix :  remove dependency from suds-jurko(unmaintained) and switch to another soap client

**Comment by snvad** [comment]
Quick fix worked (`pip3 install --upgrade --no-cache-dir setuptools==58.0.1`).
I will wait for permanent fix.
Thanks!

**Comment by smallfish01** [comment]
> pip3 install --upgrade --no-cache-dir setuptools==58.0.1

Thanks for your replied, now I have resolved this issus.

Thank you again.
