### ISSUE TITLE
How can I use an existing vmdk file to create VM? Can some one give me a example?

### ISSUE THREAD

**Issue by DamonLiang2021** [vmware/vsphere-automation-sdk-python#293]
- [ ] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [ ] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [ ] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
nsx-vmc-aws-integration-python-sdk 3.1.3.2.0
nsx-vmc-policy-python-sdk          3.1.3.2.0
pyvim                              3.0.2
pyvmomi                            7.0.3
ubuntu-advantage-tools             27.2
ubuntu-drivers-common              0.0.0
vapi-client-bindings               3.7.0
vapi-common-client                 2.30.0
vapi-runtime                       2.30.0
vmc-client-bindings                1.54.0
vmc-draas-client-bindings          1.18.0
vSphere-Automation-SDK             1.71.0
- python version:

- vSphere version: Python 3.8.10

- Operating System/Shell (used to run SDK-based apps):
Linux myubu-virtual-machine 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

## Steps or code snippet to reproduce

        boot_disk = Disk.CreateSpec(type=Disk.HostBusAdapterType.SCSI,
                                    scsi=ScsiAddressSpec(bus=0, unit=0),
                                    new_vmdk=Disk.VmdkCreateSpec())
        data_disk = Disk.CreateSpec(new_vmdk=Disk.VmdkCreateSpec())

        nic = Ethernet.CreateSpec(
            start_connected=True,
            backing=Ethernet.BackingSpec(
                type=Ethernet.BackingType.STANDARD_PORTGROUP,
                network=standard_network))

        boot_device_order = [
            BootDevice.EntryCreateSpec(BootDevice.Type.ETHERNET),
            BootDevice.EntryCreateSpec(BootDevice.Type.DISK)]

        vm_create_spec = VM.CreateSpec(name=self.vm_name,
                                       guest_os=guest_os,
                                       placement=self.placement_spec,
                                       disks=[boot_disk, data_disk],
                                       nics=[nic],
                                       boot_devices=boot_device_order)
## Actual behavior
The code above only to create new disk for the VM.

## Expected behavior
How to modify the code to create VM by using existing vmdk file?

**Comment by jobingeo** [comment]
To use an existing vmdk file, you need to detach the vmdk from an existing vm (part 1) and attach it to another vm (part 2). Below are some of the snippets that can be referred,

You can refer disk class for the same: https://vmware.github.io/vsphere-automation-sdk-python/vsphere/7.0.2.0/com.vmware.vcenter.vm.html#com.vmware.vcenter.vm.hardware_client.Disk
from com.vmware.vcenter.vm.hardware_client import Disk

part 1: Identify the the existing vmdk. 
disk_info = Disk.get(vm=vm_id, disk=disk_id)
disk_vmdk_path = disk_info.backing.vmdk_file
log.info("disk_vmdk_path '%s'" % disk_vmdk_path)
//Detach from a VM
Disk.delete(vm=vm_id, disk=disk_id)
```
Note:
 The Disk.delete() method provides the ability to detach a VMDK file from the virtual machine. The Disk.delete() method does not delete the VMDK file that backs the virtual disk. Once detached, the VMDK file will not be destroyed when the virtual machine to which it was associated is deleted.
```
part 2: Use the detached vmdk and form a backing spec and use it in  create  disk spec
new_disk_backing_spec = Disk.BackingSpec(  type=Disk.BackingType.VMDK_FILE, vmdk_file=disk_vmdk_path)
data_disk = Disk.CreateSpec(backing=new_disk_backing_spec)
.. and use this in VM.CreateSpec(..disks=[boot_disk, data_disk]...)
