### ISSUE TITLE
Update Content Library storage backings

### ISSUE THREAD

**Issue by jm66** [vmware/vsphere-automation-sdk-python#300]
### Describe the bug

Updating a content library storage backings does not work with the following code:

```
library_id = '<valid_lib_id>'
datastore_mo_id = '<valid_ds_id>'

update_spec = LibraryModel()
update_spec.storage_backings = [StorageBacking(type=StorageBacking.Type.DATASTORE, datastore_id=datastore_mo_id)]
self.client.local_library_service.update(library_id, update_spec)

```

### Reproduction steps

```bash
1. Update content library backings with the following code:

library_id = '<valid_lib_id>'
datastore_mo_id = '<valid_ds_id>'

update_spec = LibraryModel()
update_spec.storage_backings = [StorageBacking(type=StorageBacking.Type.DATASTORE, datastore_id=datastore_mo_id)]
self.client.local_library_service.update(library_id, update_spec)


2. Storage backings not updated and no error is thrown.
```

### Expected behavior

Either storage backing is updated as specified or feedback is provided.

**Comment by kunalpmj** [comment]
Content Library storage backing can not be updated.
https://vdc-download.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/operations/com/vmware/content/library.update-operation.html

update_spec.storage_backings	[storage_backing](https://vdc-download.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/structures/com/vmware/content/library/storage_backing-structure.html)[]	The list of storage backings which are available for this library.
A [content.library.storage_backing](https://vdc-download.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/structures/com/vmware/content/library/storage_backing-structure.html) defines a storage location which can be used to store files for the library items in this library. Multiple storage locations are not currently supported but may become supported in future releases.

Optional. This field must be provided for the create operation. It will always be present in the result of the get or list operations. It is not used for the update operation.
