### ISSUE TITLE
vapi-runtime requires requests==2.6.0

### ISSUE THREAD

**Issue by linuxdan** [vmware/vsphere-automation-sdk-python#31]
I have requests (2.18.3) installed.
Can it work with the newer version ?

**Comment by pgbidkar** [comment]
Verified with requests version 2.8.14.  It works with latest requests version
Please let me know if you find any issue

>>> import requests
>>> requests.__version__
'2.18.4'
>>>

**Comment by linuxdan** [comment]
So then how do we get vapi_runtime-2.5.0/vapi_runtime.egg-info/requires.txt updated ?

**Comment by linuxdan** [comment]
cat vapi_runtime-2.5.0/vapi_runtime.egg-info/requires.txt
setuptools
simplejson>=3.6.5
pyOpenSSL==0.15.1
requests==2.6.0
six==1.9
werkzeug==0.10.4


And how about considering a change to the other absolute (==) requirements to relative  (>=) ones ?

**Comment by tianhao64** [comment]
@linuxdan Thanks for reporting this. This will be fixed in the upcoming release.

**Comment by tianhao64** [comment]
This is fixed as part of release v6.6.1
