### ISSUE TITLE
Ability to retrieve enviorement certificates of VCSA

### ISSUE THREAD

**Issue by belykhk** [vmware/vsphere-automation-sdk-python#313]
### Is your feature request related to a problem? Please describe.

For purpose of monitoring i need to retrive information about expire date of various certificates stored in vCenter. I can see them if i login to VCSA by ssh and run `for store in $(/usr/lib/vmware-vmafd/bin/vecs-cli store list | grep -v TRUSTED_ROOT_CRLS); do echo "[*] Store :" $store; /usr/lib/vmware-vmafd/bin/vecs-cli entry list --store $store --text | grep -ie "Alias" -ie "Not After";done;` as described [here](https://kb.vmware.com/s/article/82332). 

I can't find any information about retrieving all af those certs, besides of `machine ssl` and `trusted root` ones. If there is way to do it outside of ssh cli, i'd like to know.

### Describe the solution you'd like

Ability to retrieve all VCSA certificates with information about expire date

**Comment by kunal-pmj** [comment]
Refer to following API reference. https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/certificate_management/vcenter.trusted_root_chains/ 
Python API doc : https://vmware.github.io/vsphere-automation-sdk-python/vsphere/8.0.2.0/com.vmware.vcenter.certificate_management.html
