### ISSUE TITLE
list_vms.py does not

### ISSUE THREAD

**Issue by linuxdan** [vmware/vsphere-automation-sdk-python#32]
Traceback (most recent call last):
  File "./list_vms.py", line 61, in <module>
    main()
  File "./list_vms.py", line 57, in main
    run()
  File "./list_vms.py", line 46, in run
    list_of_vms = vm_svc.list()
  File "/usr/lib/python2.7/site-packages/com/vmware/vcenter_client.py", line 3077, in list
    'filter': filter,
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py", line 238, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py", line 197, in native_invoke
    self._config.resolver)
com.vmware.vapi.std.errors_client.OperationNotFound: {data : None, messages : [LocalizableMessage(default_message="Cannot find service 'com.vmware.vcenter.VM'.", args=['com.vmware.vcenter.VM'], id='vapi.method.input.invalid.interface')]}

**Comment by tianhao64** [comment]
@linuxdan Have you successfully installed the 6.5 bindings and runtime packages?

**Comment by linuxdan** [comment]
No clue what you referring to.
I installed this python library.

**Comment by pgbidkar** [comment]
You need to install required Libraries present in lib dir
run command $pip install -r requirements.txt from cloned dir

Please refer https://github.com/vmware/vsphere-automation-sdk-python#installing-the-required-python-packages, for more info

**Comment by linuxdan** [comment]
Already did that.  A "pip list" includes
vapi-client-bindings (2.5.0)
vapi-common-client (2.5.0)
vapi-runtime (2.5.0)

But they are not "6.5"

**Comment by linuxdan** [comment]
FWIW, we have vCenter 6.0 running

**Comment by pgbidkar** [comment]
Tagging & Content Library samples work with 6.0
VM lifecycle samples work with 6.5+ versions

**Comment by Carlimeunier** [comment]
Hello, 
I have the same issues with list_vm. I have a VCSA 6.0

Any idea?

**Comment by tianhao64** [comment]
@linuxdan @Carlimeunier As Pavan mentioned the vm lifecycle APIs are introduced since vSphere 6.5. They are not available for VCSA 6.0. 
For VCSA 6.0, you can use content library and tagging APIs. 
There is a comment on top of each sample which indicates the required vSphere version. For list_vms.py has "__vcenter_version__ = '6.5+'", meaning the API only works for vCenter 6.5+.

**Comment by madexuan** [comment]
Does the VCSA 6.0 api support virtual machine creation?

**Comment by tianhao64** [comment]
No. VM lifecycle APIs are introduced in 6.5.
