### ISSUE TITLE
code repository URL in getting started steps need to be updated

### ISSUE THREAD

**Issue by vThinkBeyondVM** [vmware/vsphere-automation-sdk-python#334]
### Describe the bug

Under getting started readme guide, we have below section and URL mentioned seems internal only. Can you please update the documentation? 

Install SDK packages from Github.

pip install --upgrade git+https://gitlab.eng.vmware.com/vapi-sdk/vsphere-automation-sdk-python.git

### Reproduction steps

Described above

### Expected behavior

Correct github URL is needed

**Comment by shwetapurohit** [comment]
@vThinkBeyondVM thanks for pointing ! Updated the README with correct url.
