### ISSUE TITLE
Cannot find service 'com.vmware.vcenter.vm.guest.power'

### ISSUE THREAD

**Issue by Jean-PhilippeD** [vmware/vsphere-automation-sdk-python#343]
### Describe the bug

Hello,
I'm trying to use the SDK so I started with sample, and tried to shutdown a VM with guest method and here is what I get: 

`{'_output': None, '_error': StructValue(name='com.vmware.vapi.std.errors.operation_not_found', values={'data': OptionalValue(None), 'messages': ListValue(values=[StructValue(name='com.vmware.vapi.std.localizable_message', values={'args': ListValue(values=[StringValue(value='com.vmware.vcenter.vm.guest.power')], is_map=False), 'default_message': StringValue(value="Cannot find service 'com.vmware.vcenter.vm.guest.power'."), 'id': StringValue(value='vapi.method.input.invalid.interface')})], is_map=False)})}
`
I can stop the VM with the Hard way, but no matter what I do with guest, it doesn't work (I tried guest.identity and I got same issue)

### Reproduction steps

1. Create a _vsphere_client()_ - works
2. Get the vm list with _self.vsphere_client.vcenter.VM.list(VM.FilterSpec(names=names))_ - works
3. On each VM, I try to stop it with _self.vsphere_client.vcenter.vm.guest.Power.shutdown(vm)_
and here it fails

### Expected behavior

I'd like the VM to be stopped smooth with Vmware tools.
It works if I stopped if from Vsphere client with tools.

**Comment by mtsvetanov** [comment]
Hi @Jean-PhilippeD, what URL you are connecting the client to? What is the version of the vCenter?

**Comment by Jean-PhilippeD** [comment]
Hi,
I connect to the vcenter with ths FQDN, the vcenter's version is 6.5.0.37

**Comment by mtsvetanov** [comment]
Thanks, @Jean-PhilippeD!

This API is only added in vSphere 6.7 as documented in this SDK's [reference doc](https://vmware.github.io/vsphere-automation-sdk-python/vsphere/8.0.0.1/com.vmware.vcenter.vm.html?highlight=power#com.vmware.vcenter.vm.guest_client.Power).

That is why your 6.5 server doesn't have it, and responds with _com.vmware.vapi.std.errors.operation_not_found_ error.

**Comment by Jean-PhilippeD** [comment]
Thank you for the link, I did not found this information.
The tests we made manuaylly was wrong so we thought we could use the API :'(
