### ISSUE TITLE
How to get power consumption of VMHost?

### ISSUE THREAD

**Issue by JanLucasK** [vmware/vsphere-automation-sdk-python#344]
### Is your feature request related to a problem? Please describe.

Hello, I would be very grateful for help with my problem.

I would like to query the energy consumption of my VMHosts, however I cannot find such a value/property. The closest I have come to are the values of various sensors via the Property Collector and 'runtime.healthSystemRuntime.systemHealthInfo.numericSensorInfo'. These values with the sensorType='power' added together make sense, but are not updated at the interval that power consumption is in vSphere. In vSphere the power consumption is shown every 20 seconds and the timestamps of the sensors (with this API) are hours old. Is there an easier way or is it even possible with this API?

Thanks in advance

### Describe the solution you'd like

I would like to query the current power consumption of my VMHosts.

**Comment by mtsvetanov** [comment]
You might be interested in the [vStats APIs](https://developer.vmware.com/apis/vsphere-automation/latest/vstats/vstats/) which are covered by this SDK. I believe power consumption is available there, but you would have to check what counters are actually supported.

**Comment by JanLucasK** [comment]
That sounds promising, thank you very much :)

**Comment by karaatanassov** [comment]
You can use govmomi, pyvmomi, the Management SDK or PowerCli and inquire power consumption through the PerformanceManager

See 
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1ef6c336-7bef-477d-b9bb-caa1767d7e30/82521f49-9d9a-42b7-b19b-9e6cd9b30db1/vim.PerformanceManager.html
