### ISSUE TITLE
下载依赖包报错

### ISSUE THREAD

**Issue by Echo-ZhangXu** [vmware/vsphere-automation-sdk-python#345]
### Describe the bug

ERROR: Could not find a version that satisfies the requirement vapi-client-bindings==4.0.0 (from -r requirements.txt (line 2)) (from versions: 7.0.0)
ERROR: No matching distribution found for vapi-client-bindings==4.0.0 (from -r requirements.txt (line 2))

### Reproduction steps

python2.7 -m pip install -r requirements.txt

### Expected behavior

ERROR: Could not find a version that satisfies the requirement vapi-client-bindings==4.0.0 (from -r requirements.txt (line 2)) (from versions: 7.0.0)
ERROR: No matching distribution found for vapi-client-bindings==4.0.0 (from -r requirements.txt (line 2))

**Comment by aagrawal3** [comment]
Hi @Echo-ZhangXu 

Pleases follow the installation steps provided in README.
https://github.com/vmware/vsphere-automation-sdk-python#quick-start-guide

We also recommend moving to Python 3.8+ as our latest release is not tested to support Python 2.x
