### ISSUE TITLE
samples/vsphere/common/sso.py broken with pyVmomi version 8.0.0.1

### ISSUE THREAD

**Issue by crashingmotorbikes** [vmware/vsphere-automation-sdk-python#349]
### Describe the bug

Line 31 of samples/vsphere/common/sso.py performs an import of ThumbprintMismatchException from pyVmomi. In the latest version of pyVmomi, this cannot be found for import.

### Reproduction steps

1.pip install pyVmomi
2.Set PYTHONPATH to reference samples
3.Try to import sso from samples.vsphere.common
...

### Expected behavior

Would expect sso to import fine.

**Comment by crashingmotorbikes** [comment]
#350

**Comment by shwetapurohit** [comment]
Hi @crashingmotorbikes :
This is an incompatibility problem with pyvmomi 8.0.0.1. The SDK will only be compatible with versions of pyVmomi up to 7.0.3 while we are working on the pyVmomi fix.

Thanks!

**Comment by kunal-pmj** [comment]
Issues has been fixed with release : https://github.com/vmware/vsphere-automation-sdk-python/releases/tag/v8.0.1.0
