### ISSUE TITLE
Deployment of external OVF files, i.e. not present in Content Library

### ISSUE THREAD

**Issue by aleksandar-kinanov** [vmware/vsphere-automation-sdk-python#351]
### Is your feature request related to a problem? Please describe.

I am trying to automate deployment of OVF files, but it seems that you cannot do that with the Python SDK as of now.
 I also need to tag my VMs, which cannot be done via PyVmomi, I need two separate client/connections

### Describe the solution you'd like

Extension of the SDK to support OVF deployment as you can do the same with PyVmomi.

### Describe alternatives you've considered

I am currently deploying it using PyVmomi

**Comment by shwetapurohit** [comment]
@aleksandar-kinanov :
OVF deployment without a content library is not yet supported by vAutomationSDK.

**Comment by aleksandar-kinanov** [comment]
@shwetapurohit thanks a lot for the answer!

Any idea if it will be supported in the near future?

**Comment by kunal-pmj** [comment]
Hi @aleksandar-kinanov 

We do not have any immediate plan to provide REST API to deploy OVF not managed by CLS. As a workaround you can use vim API to do the same.
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1ef6c336-7bef-477d-b9bb-caa1767d7e30/82521f49-9d9a-42b7-b19b-9e6cd9b30db1/vim.ResourcePool.html#importVApp
pyvmomi can be used along with automation python SDK to do this.

thanks
Kunal
