### ISSUE TITLE
Tag name association to Tag urn

### ISSUE THREAD

**Issue by alan-cugler** [vmware/vsphere-automation-sdk-python#360]
### Is your feature request related to a problem? Please describe.

A client is asking for their vCenter Tags associated to VMs to be imported to the grains system of Aria Automation Config (open-salt). This is a good fit for integration between the two pieces of technology. I attempted to achieve this by installing the vsphere-automation-sdk in the open-salt python environment. This did work and I was able to authenticate a session to vCenter!

However, I found I was able to extract the information of VM names and VM IDs, and I was able to get Tag URNs assigned to VM IDs. But there was no way to associate the Tag URNs to the human readable Tag names.

![image](https://user-images.githubusercontent.com/25991646/212185034-173d4bb0-a33e-494d-8aeb-d6091d06d568.png)

### Describe the solution you'd like

I would like the Tag names to also be part of the data returned when calling `session.vcenter.tagging.Associations.list()`. 

Alternatively, the Tags Names ( +URNs?) could also be part of information returned from `session.vcenter.VM.get()` or `session.vcenter.VM.list()`

### Describe alternatives you've considered

- I talked to a few vCenter engineers for other ways to get the data out of vCenter in a programmable way.
- Explored if there was a way for `VMware Tools` to request information describing the guest VM from vCenter.
- Attempted to find a way to access the vCenter database where this Tag meta data might be stored.
- Looked at other vSphere APIs to see if they were more "developed" even though python is ideal.

### Additional context

VM.list() output in my PSO lab
![image](https://user-images.githubusercontent.com/25991646/212186515-36925805-1231-42ab-bc22-5131679d4ac4.png)

VM.get() output in my PSO lab
![image](https://user-images.githubusercontent.com/25991646/212186600-5e47bb4c-1f8b-400c-8cc2-6b0df2050eef.png)

Tags in my PSO lab
![image](https://user-images.githubusercontent.com/25991646/212186969-590194f9-e1e4-4640-ad7a-b1598678e5a2.png)

Tag connected to my VM that has an ID of `vm-49`
![image](https://user-images.githubusercontent.com/25991646/212187161-7bf12835-281d-4530-973d-8c99328d21c9.png)

**Comment by tldlauser** [comment]
I think this might be it: https://vdc-repo.vmware.com/vmwb-repository/dcr-public/97e6db01-d441-472e-ad53-b48c2bb0e1e4/45347fb1-052d-44b7-b3e9-cbefc34488e3/SDK/vsphere-ws/docs/ReferenceGuide/vim.Tag.html

**Comment by tldlauser** [comment]
This one seems better. https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/tagging/ The whitepaper it references says, "To retrieve tag names from these IDs, you must use get() calls. For example, Tag.get() returns a TagModel object that has name, id, category_ id, description, and used_by fields."

**Comment by kunal-pmj** [comment]
Thanks @tldlauser for answering how to get the tag properties from tag id. 
@alan-cugler  
In the associations, providing attributes other than id is not desirable

Kindly used the getTag API to get the name .

I am closing the issue.

Thanks
Kunal

**Comment by alan-cugler** [comment]
I request this be reopened to at least explain how to get tags, the White paper does not clearly specify how to get tag name to vm associations clearly. It makes up alot of its own api calls that are not in the official api.

**Comment by kunal-pmj** [comment]
Kindly refer to the sample on how to get the tag from tag_id
https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/tagging/tagging_workflow.py#L173

From tag association get the tag_id and pass it to the 
client.tagging.Tag.get(tag_id)
