### ISSUE TITLE
Upgrade Cryptography 36.0.0 to 39.0.1 or higher if possible

### ISSUE THREAD

**Issue by IAmAStealer** [vmware/vsphere-automation-sdk-python#369]
### Is your feature request related to a problem? Please describe.

Hello, 
Regarding CVEs for the version 36.0.0 that can be high, is it possible to upgrade to a newer version of cryptography ?
My problems comes for virtualenv that requires higher version of cryptography for security but vsphere-automation-sdk-python requirements blocks the upgrade.

### Describe the solution you'd like

Update cryptography requirement to 39.0.1

**Comment by aagrawal3** [comment]
Addressed in https://github.com/vmware/vsphere-automation-sdk-python/pull/372
