### ISSUE TITLE
No Monitoring APIs part of the SDK yet?

### ISSUE THREAD

**Issue by asifaaag** [vmware/vsphere-automation-sdk-python#37]
Hi,

Are the monitoring APIs not part of this automation sdk yet?

Regards,
Asif

**Comment by tianhao64** [comment]
@asifaaag Appliance monitoring API bindings are part of the automation SDK already. However there is no samples on github yet. For sample code, you can refer to: https://vdc-download.vmware.com/vmwb-repository/dcr-public/cdd3166b-c90d-408a-9df5-28dda80f2e3a/d04efb15-e870-44a2-82f7-44861a39923a/vcenter-server-appliance-sdk-65-python-programming-guide.pdf

API spec is available at: https://vdc-download.vmware.com/vmwb-repository/dcr-public/d4c03018-5f5b-4cd8-b19e-bd18baedc9ad/8384359f-39bb-4499-b7c5-9bd2e1a7330f/doc/client/com.vmware.appliance.techpreview.html#module-com.vmware.appliance.techpreview.monitoring_client

**Comment by asifaaag** [comment]
@tianhao64 The API spec that you have pointed me to is the techpreview SNMP monitoring API, I was taking about:


Operation | HTTP request | Description
-- | -- | --
get | GET https://{server}/rest/appliance/monitoring/{stat_id} | Get monitored item info
list | GET https://{server}/rest/appliance/monitoring | Get monitored items list
query | GET https://{server}/rest/appliance/monitoring/query | Get monitoring data.


I dont see bindings for these as part of the API yet? Correct me if Im wrong.
