### ISSUE TITLE
Sample code doesn't return VM.List()

### ISSUE THREAD

**Issue by giriatgit** [vmware/vsphere-automation-sdk-python#381]
### Describe the bug

The sample given at https://github.com/vmware/vsphere-automation-sdk-python/tree/v8.0.0.1

import requests
import urllib3
from vmware.vapi.vsphere.client import create_vsphere_client
session = requests.session()

# Disable cert verification for demo purpose. 
# This is not recommended in a production environment.
session.verify = False

# Disable the secure connection warning for demo purpose.
# This is not recommended in a production environment.
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Connect to a vCenter Server using username and password
vsphere_client = create_vsphere_client(server='<vc_ip>', username='<vc_username>', password='<vc_password>', session=session)

# List all VMs inside the vCenter Server
vsphere_client.vcenter.VM.list()

This code doesn't return the list of VMs even hough I have 2 vms created in vCenter/ESXi.

The output is just blank..

(vCenterDemo) (base) $ python vCClient.py 
(vCenterDemo) (base) $ 

### Reproduction steps

1.
2.
3.
...

### Expected behavior

List of VMs in the vCenter

**Comment by aagrawal3** [comment]
Please share following details:
- [Installation type](https://github.com/vmware/vsphere-automation-sdk-python#installing-required-python-packages): typical/local/air-gapped
- Environment details such as Python, Setuptools and pip version.
- Steps to reproduce

Our [listVM sample](https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/vcenter/vm/list_vms.py) is also available in samples dir and detailed instructions to install SDK and run samples are available in [README](https://github.com/vmware/vsphere-automation-sdk-python#table-of-contents). Please refer to [quick start guide](https://github.com/vmware/vsphere-automation-sdk-python#quick-start-guide) and [run SDK samples](https://github.com/vmware/vsphere-automation-sdk-python#run-sdk-samples) sections.

**Comment by girishkumarbk** [comment]
Installation type is Typical.

(vCenterDemo) (base) girish$ pip3 --version
pip 23.1.2 from /Users/../lib/python3.7/site-packages/pip (python 3.7)
(vCenterDemo) (base) girish$ 
(vCenterDemo) (base) girish$ 
(vCenterDemo) (base) girish$ python3 --version
Python 3.7.6
(vCenterDemo) (base) girish$ 
(vCenterDemo) (base) girish$

Steps to reproduce:
(1) Update the sample code with vCenter server ip, user credentials
(2) Run python3 my sample.py (The code is pasted in earlier message) The sample given at https://github.com/vmware/vsphere-automation-sdk-python/tree/v8.0.0.1

**Comment by aagrawal3** [comment]
Please try this (replace values in placeholders for IP, Username and Password):

```
import requests
import urllib3
from vmware.vapi.vsphere.client import create_vsphere_client
session = requests.session()

# Disable cert verification for demo purpose.
# This is not recommended in a production environment.
session.verify = False

# Disable the secure connection warning for demo purpose.
# This is not recommended in a production environment.
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Connect to a vCenter Server using username and password
vsphere_client = create_vsphere_client(server='<vc_ip>', username='<vc_username>', password='<vc_password>', session=session)

# List all VMs inside the vCenter Server
list_of_vms = vsphere_client.vcenter.VM.list()

print("List Of VMs")
print("----------------------------")
print(list_of_vms)
print("----------------------------")
```

**Comment by girishkumarbk** [comment]
Hi. Just tried the above code. but still no Vms.

(vCenterDemo) (base) girish$ python3 vCClient2.py
List Of VMs
----------------------------
[]
----------------------------

**Comment by girishkumarbk** [comment]
(vCenterDemo) (base) girish $ python3 vCClient2.py
List Of VMs
----------------------------
[ ]
----------------------------

**Comment by girishkumarbk** [comment]
Nevermind.  Got the output.

Summary(vm='vm-16', name='vm-001', power_state=State(string='POWERED_ON'), cpu_count=2, memory_size_mib=8192)]

**Comment by girishkumarbk** [comment]
Thanks.
