### ISSUE TITLE
Permissions to access appliance_client.Monitoring

### ISSUE THREAD

**Issue by skywalk7** [vmware/vsphere-automation-sdk-python#39]
According to https://pubs.vmware.com/vsphere-6-5/index.jsp#com.vmware.vsphere.vcsapg-rest.doc/GUID-D7469D6F-5778-48B7-9AEB-865EC3E2226F.html I've added my account to _"ComponentManager.Administrator"_ vCenter Single Sign-On Group. But it still throws error:
`{messages : [LocalizableMessage(id='vapi.security.authorization.invalid', default_message='Unable to authorize user', args=[])], data : None}`
But it works when I add account to _SystemConfiguration.Administrators_ group.
Relevant part of code:
>     monitoring = appliance_client.Monitoring(config)
>     items = monitoring.list()

**Comment by tianhao64** [comment]
@skywalk7 I have reached out to the appliance management team. Will provide update soon.

**Comment by naltanov** [comment]
The doc has been updated.

**Comment by tianhao64** [comment]
@naltanov Thanks. @skywalk7 Please verify.

**Comment by skywalk7** [comment]
@tianhao64 @naltanov Thanks a lot! It would be better to have account with read only permissions to monitor health state. Hope you can address it in the future.
