### ISSUE TITLE
pip install vsphere-automation-sdk-python is broken.

### ISSUE THREAD

**Issue by yixingjia** [vmware/vsphere-automation-sdk-python#392]
### Describe the bug

Seems we have a long time didn't update the packages on the https://pypi.org/project/vsphere-automation-sdk-python/ site. 

```
pip install vsphere-automation-sdk-python
Collecting vsphere-automation-sdk-python
  Downloading vsphere-automation-sdk-python-0.0.1.tar.gz (981 bytes)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/wn/80ngj5mj0035ppnv6f5pcp7c0000gn/T/pip-install-rx2tqz1h/vsphere-automation-sdk-python_d681a1fb61e94601ba13ba3487cdf0d0/setup.py", line 13, in <module>
          license=read('LICENSE.txt'),
        File "/private/var/folders/wn/80ngj5mj0035ppnv6f5pcp7c0000gn/T/pip-install-rx2tqz1h/vsphere-automation-sdk-python_d681a1fb61e94601ba13ba3487cdf0d0/setup.py", line 5, in read
          with open(os.path.join(os.path.dirname(__file__), fname)) as fn:
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/wn/80ngj5mj0035ppnv6f5pcp7c0000gn/T/pip-install-rx2tqz1h/vsphere-automation-sdk-python_d681a1fb61e94601ba13ba3487cdf0d0/LICENSE.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

### Reproduction steps

1. pip install vsphere-automation-sdk-python
2.
3.
...

### Expected behavior

vsphere-automation-sdk-python should installed.

**Comment by aagrawal3** [comment]
This SDK is not on PyPI yet. Please refer to [README](https://github.com/vmware/vsphere-automation-sdk-python#vmware-vsphere-automation-sdk-for-python) for installation instructions. 

[PyPI project](https://pypi.org/project/vsphere-automation-sdk-python/#description) was published to reserve the project name. It is a dummy project for future publishing needs and to avoid supply chain attacks.

**Comment by yixingjia** [comment]
@aagrawal3 Do we have plan to make it available on pypi ?  We have anyother project that will build build as a pypi project and in the setup we want to include vsphere-automation-sdk-python

**Comment by aagrawal3** [comment]
Yes, it is in our pipeline. Unfortunately, I can not provide a timeline.
