### ISSUE TITLE
How to get list of running Tasks ?

### ISSUE THREAD

**Issue by harukinakazono** [vmware/vsphere-automation-sdk-python#410]
Hello,
I use vcenter 8.0

How do I do get list of running Tasks related  a VM? How can I do that? I've tried searching this on the [documents](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/d29017d5-9c5b-4329-8320-1c41fbfe23a2/5c3cda98-2875-47cf-87dc-327848bd31fb/vsphere-automation-sdk-python-gh-pages/vsphere/8.0.1.0/com.vmware.html).

Please give any informations and I want some samples.

**Comment by shwetapurohit** [comment]
@harukinakazono :
Try below rest api to get the Tasks -
https://developer.vmware.com/apis/vi-json/latest/sdk/vim25/release/TaskManager/moId/recentTask/get/

**Comment by harukinakazono** [comment]
> @harukinakazono : Try below rest api to get the Tasks - https://developer.vmware.com/apis/vi-json/latest/sdk/vim25/release/TaskManager/moId/recentTask/get/

Thank you.
Sorry for the lack of explanation.
I want to know how to get the task using the vsphere-automation-sdk-python package.
Please tell me how to get it and give me an example of it.

Thanks.
