### ISSUE TITLE
How to get list of running Tasks using vsphere-automation-sdk-python? 

### ISSUE THREAD

**Issue by harukinakazono** [vmware/vsphere-automation-sdk-python#412]
### Is your feature request related to a problem? Please describe.

I want to know how to get tasks using the vsphere-automation-sdk-python package.
Please give any informations and I want some samples.

How can I do that? I've tried searching this on the [socuments.](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/d29017d5-9c5b-4329-8320-1c41fbfe23a2/5c3cda98-2875-47cf-87dc-327848bd31fb/vsphere-automation-sdk-python-gh-pages/vsphere/8.0.1.0/com.vmware.html)

**Comment by kunalpmj** [comment]
API is available under VI JSON : https://developer.vmware.com/apis/vi-json/latest/task-manager/

Also, pyvmomi can be be used to get Task Manager getRecent_Task API.
