### ISSUE TITLE
Add "Rename" to VM operations

### ISSUE THREAD

**Issue by davidanizar** [vmware/vsphere-automation-sdk-python#413]
### Is your feature request related to a problem? Please describe.

The possibility to rename a VM would be very helpful to improve test automation.

### Describe the solution you'd like

rename could be added as a VM.attribute 
Example:
self.vsphere_client.vcenter.VM.rename(VM.FilterSpec(names=names))

### Describe alternatives you've considered

I try to wrap code:
vmkfstools -i originalname.vmdk newname.vmdk
or even: set-vm

**Comment by kunalpmj** [comment]
This feature is available via the SOAP API.
Kindly refer to the API Documentation.
https://developer.vmware.com/apis/vi-json/latest/sdk/vim25/release/VirtualMachine/moId/Rename_Task/post/
