### ISSUE TITLE
How to Get VM current CPU and Memory Usage by Python SDK

### ISSUE THREAD

**Issue by x-zhao-res** [vmware/vsphere-automation-sdk-python#416]
### Is your feature request related to a problem? Please describe.

Vision vCenter: 7.0.3
Hi,I want get vm CPU current usage but i use this code:

```
vsphere_client = create_vsphere_client(server='192.168.75.82', username='username', password='password')

vmName = ''
# List all VMs inside the vCenter Server
vmList = vsphere_client.vcenter.VM.list()
for item in vmList:
    print(item)
    vmName = item.vm
instanceVM = vsphere_client.vcenter.VM.get(vmName)
```
 only get     **_[cpu : {count : 1, cores_per_socket : 1, hot_add_enabled : False, hot_remove_enabled : False}]_** 

By the way, i search maybe it use CID like this 'cpu.usage.PCPU' but i don`t know how to use it.....

### Describe the solution you'd like

i want get VM current usage 
CPU,Memory,Disk
like this ↓

<img width="251" alt="2762882f19991c1380c90f83608e3380" src="https://github.com/vmware/vsphere-automation-sdk-python/assets/77577329/a1b8803f-98b1-4449-9ce8-ec55170b0611">

**Comment by jobingeo** [comment]
You can try [pyVmomi SDK ](https://github.com/vmware/pyvmomi)to obtain VM CPU and Memory.
Checkout this example https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/vm_perf_example.py
