### ISSUE TITLE
Outdated pip package

### ISSUE THREAD

**Issue by JeffTurner69** [vmware/vsphere-automation-sdk-python#417]
### Describe the bug

I am not able to install the sdk using pip package but I am required to do so due to company policies. The package seems to be outdated: https://pypi.org/project/vsphere-automation-sdk-python/. Is it possible to update the package? 

Error:
python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-mz8l2ywz/vsphere-automation-sdk-python_f77acd639bf64c26a0048e5785f9fcb2/setup.py", line 13, in <module>
          license=read('LICENSE.txt'),
        File "/tmp/pip-install-mz8l2ywz/vsphere-automation-sdk-python_f77acd639bf64c26a0048e5785f9fcb2/setup.py", line 5, in read
          with open(os.path.join(os.path.dirname(__file__), fname)) as fn:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-mz8l2ywz/vsphere-automation-sdk-python_f77acd639bf64c26a0048e5785f9fcb2/LICENSE.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

### Reproduction steps

1.pip install vsphere-automation-sdk-python

### Expected behavior

Successful installation of the package.

**Comment by bhagatp10** [comment]
The package on pypi is just the reserved namespace, there are no deliverables in it. If you want to install the sdk, you can follow [these steps](https://github.com/vmware/vsphere-automation-sdk-python?tab=readme-ov-file#installing-required-python-packages).
