### ISSUE TITLE
Failure to Create Session with vSphere Client Using Self-Signed Certificate

### ISSUE THREAD

**Issue by AradCarmi** [vmware/vsphere-automation-sdk-python#419]
### Describe the bug

The `create_vsphere_client` function encountered an issue when attempting to establish a session with a self-signed server, despite having the session object configured with verify=False. This failure was triggered by an SSLError, specifically an SSLZeroReturnError (error code 6), indicating that the TLS/SSL connection was closed unexpectedly (EOF) at line 997 

### Reproduction steps

1. Create a self-signed server.
2. Create a Session object with `session.verify=false`.
3. create a Python script calling the `create_vsphere_client` with server, username&password, and session.
4. Run the script.

### Expected behavior

The created session will allow us to connect the VMware Vcenter server even if the server is a self-signed certificate.

**Comment by AradCarmi** [comment]
Hey @bhagatp10 thank you for the fast response!
My VC server is updated with self-signed certificates and it is working fine. I'm trying to retrieve some data using the Client and I want the Client not to verify my certificate when creating the session. As I mentioned before, I tried to send a session object to the Client with the right configuration but from viewing the Client code it ignored this configuration.

**Comment by bhagatp10** [comment]
Hi,
Can you show me the snippet of the code you are using?

**Comment by AradCarmi** [comment]
Sure.
![image](https://github.com/vmware/vsphere-automation-sdk-python/assets/62752352/c312bef5-7055-4760-80e6-d79943ecbee5)

**Comment by kunalpmj** [comment]
What python version you are using?
What are the urllib3 and openssl version?

**Comment by AradCarmi** [comment]
python version 3.10.14
urllib3 version 2.2.1

**Comment by kunalpmj** [comment]
Kindly refer to following troubleshooting section.

https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting#certificate-verification-failed-when-making-api-calls
