### ISSUE TITLE
ModuleNotFoundError: No module named 'vmware.vapi'; 'vmware' is not a package

### ISSUE THREAD

**Issue by ThiBot77** [vmware/vsphere-automation-sdk-python#420]
### Describe the bug

Hello, 

I'm experiencing a problem following installation via typical installation and a code execution test. 

I get a module not found error
![image](https://github.com/vmware/vsphere-automation-sdk-python/assets/87268655/806c8943-a4b1-4df8-9834-60df4fa0d800)

I don't think I'm missing anything, I'm experiencing this problem on my Windows PC and my Linux server.
![image](https://github.com/vmware/vsphere-automation-sdk-python/assets/87268655/79e5d90b-043f-45b8-a34a-5b1a110704b1)

I tried the command 
set PYTHONPATH=%cd%;%PYTHONPATH%

It didn't change anything

Thank you for you help

### Reproduction steps

1. pip install --upgrade pip
2. pip install --upgrade setuptools
3. pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git
4. set PYTHONPATH=%cd%;%PYTHONPATH%
5. Launch code template "Connect to a vCenter Server"

### Expected behavior

I'd like to launch my code

**Comment by shwetapurohit** [comment]
@ThiBot77 
Please try the installation steps after the python virtual environment is setup.
Here is the step - https://github.com/vmware/vsphere-automation-sdk-python?tab=readme-ov-file#prepare-a-python-development-environment

**Comment by kunalpmj** [comment]
is python not included in the PATH?
wondering why you need to give the absolute path to python.exe? 
and what is this vmware.py? 
if this is one of your files then rename it to something else, it is conflicting with the package name "vmware"

**Comment by ThiBot77** [comment]
> is python not included in the PATH? wondering why you need to give the absolute path to python.exe? and what is this vmware.py? if this is one of your files then rename it to something else, it is conflicting with the package name "vmware"

Hi, thank you for your help.

Stupid me, my code file had the same name as the vmware module. Renaming corrected the problem
