### ISSUE TITLE
Trying to remove a member from NSServicegroup using SDK getting Concurrent change error

### ISSUE THREAD

**Issue by karthikdhanusu** [vmware/vsphere-automation-sdk-python#428]
### Describe the bug

I am trying to remove a NSservice member from NSservicegroup using SDK I am getting the below error. 

  File "C:\kdhanusu\lib\site-packages\vmware\vapi\bindings\stub.py", line 295, in native_invoke
    raise TypeConverter.convert_to_python(method_result.error,  # pylint: disable=E0702
com.vmware.vapi.std.errors_client.ConcurrentChange: {messages : [], data : {}, error_type : None}

### Reproduction steps

I am trying to remove the highlighted NSservice from NSservicegroup member 

### NSservicegroup GET response:
{links : None, schema : None, self_ : None, revision : 0, create_time : 1726588666018, create_user : nsx_policy, last_modified_time : 1726588666018, last_modified_user : nsx_policy, protection : REQUI
RE_OVERRIDE, system_owned : False, description : test23, display_name : Test1, id : 11775959-1ad7-40ed-ba92-c7e60d04d2ba, resource_type : NSServiceGroup, tags : None, default_service : False, members
: [_**ResourceReference(is_valid=True, target_display_name='test2345', target_id='33e4c2c4-56a3-4949-974c-425777699249', target_type='NSService')**_, ResourceReference(is_valid=True, target_display_name='IP
123', target_id='b3e752db-702c-4df6-ba3b-7f0f423ff2a9', target_type='NSService')], service_type : NON_ETHER}

I removed the first member using python list function and parsed the updated list as a member with the same id 

1. removed the first member using python function
2. used model_client.ResourceReference class to format the existing members.  
3. used model_client.NSServiceGroup to update the formatted members .  NSServiceGroup(members=**[ResourceReference(is_valid=True, target_display_name='IP123', target_id='b3e752db-702c-4df6-ba3b-7f0f423ff2a9',target_type='NSService')]**) 

### UpdatedMember_Input:

{links : None, schema : None, self_ : None, revision : 0, create_time : None, create_user : None, last_modified_time : None, last_modified_user : None, protection : None, system_owned : None, description : None, display_name : None, id : None, resource_type : None, tags : None, default_service : None, members
: [ ResourceReference(is_valid=True, target_display_name='IP
123', target_id='b3e752db-702c-4df6-ba3b-7f0f423ff2a9', target_type='NSService')], service_type : None}

4. used the function NsServiceGroups(stub).update(ns_service_group_id='11775959-1ad7-40ed-ba92-c7e60d04d2ba', ns_service_group=**UpdatedMember_Input**)  

### Expected behavior

It should remove the NSservice member from the existing NSservicegroup

**Comment by kunalpmj** [comment]
Hi @karthikdhanusu 

Can you share the code snippet?
