### ISSUE TITLE
guys, i got two questions:1,through python code, how can i check whether or not a vm has been installed OS?

### ISSUE THREAD

**Issue by BourneNeo** [vmware/vsphere-automation-sdk-python#43]

**Comment by BourneNeo** [comment]
1,through python code, how can i check whether or not a vm has been installed OS? 2, onece

**Comment by BourneNeo** [comment]
天浩老师，我有两个问题想请教您，1是我怎么用代码查看一个虚拟机是否已经装过操作系统？2是我能否在用python自动化创建虚拟机的时候就对该虚拟机进行网络设置，分配一个IP,这样我在创建好虚拟机，然后装好系统之后，不用手动登录进去配置IP 就可以使用网络服务了? 希望您方便的时候能回复我一下，谢谢。🙂

**Comment by tianhao64** [comment]
@BourneNeo You should be able to access the guest information using following API:
https://code.vmware.com/doc/preview?id=4206#/doc/vim.vm.GuestInfo.html
This API is not available automation SDK yet so you have to use pyVmomi.
You can't assign IP address without an OS installed. Here is an example about how to assign an IP address using pyVmomi: https://github.com/rreubenur/vmware-pyvmomi-examples/blob/master/network_configure.py
