### ISSUE TITLE
Help required to automate "Import VMS" options on UI

### ISSUE THREAD

**Issue by anusajith** [vmware/vsphere-automation-sdk-python#430]
### Is your feature request related to a problem? Please describe.

Hey Team, 

We are trying to provide an automated solution for importing VMs from an ESXi(eg:"esxi_source") host on a vSphere client version(6.7.0.50000)(eg:"source_client") to another ESXi host(eg: "esxi_dest") on to a vSphere client version(8.0.2.00300)(eg:"source_dest")

We are able to do it manually through the UI using the below option:

![image](https://github.com/user-attachments/assets/572ffa7a-c98f-4c00-98d2-ae635f41e358)

Can you please suggest an available function/method or if you can provide an example to do , will be of great help.

### Describe the solution you'd like

Here we have to connect to both the vSphere clients and should be able to create a VM spec using the available resource details from client_source and that spec  has to be applied to client_dest, provided the required resourcepool, datastore or any other resources are already present in the destination client.

**Comment by kunalpmj** [comment]
Hi @anusajith 

The UI feature "Import VMs" uses the relocateVM vim API(SOAP). 
Here is the vSphere Web Services API reference guide : https://dp-downloads.broadcom.com/api-content/apis/API_VWSA_001/8.0U3/html/ReferenceGuides/vim.VirtualMachine.html#relocate. and the JOAP API(JSON over SOAP) : https://developer.broadcom.com/xapis/virtual-infrastructure-json-api/latest/sdk/vim25/release/VirtualMachine/moId/RelocateVM_Task/post/.

Here is a python samples which shows usage of the relocate API https://github.com/sijis/pyvmomi-examples/blob/master/migrate-vm.py. 

Import VM use case in the UI follows a workflow involving the relocateVM at the core as there are other APIs involved building the ServiceLocator, and RelocationSpec. e.g listing of hosts, clusters, VMs, resource pool etc.

Let me know if the information is sufficient.

thanks
Kunal

**Comment by anusajith** [comment]
Hey Kunal,

 Even for us, if we do migration within a vCenter between two EXSi hosts, it is working fine. Can you please provide with an example for migrating a vm between two vCenters.

Regards,
Anu

**Comment by kunalpmj** [comment]
Perhaps, you are missing on very important ServiceLocator in the RelocationSpec. It is a must in case of cross vc VM migration to specify the target VC service (credentials for authenticating to a service endpoint, URL to access the service endpoint, instance ID etc) where the vm will be relocated.

We do not have a sample covering this exact use case. We can take this as an enhancement request. However, cannot commit on the timelines to make the sample available anytime soon. 

You need to add the ServiceLocator for cross vc VM import.

We are taking the enhancement request and closing the ticket.

Thanks
