### ISSUE TITLE
hey I try to list the name the health and the state of v center services witch can found in (administration ->system configuration->services) version 6.0 please help???

### ISSUE THREAD

**Issue by rimsaoud** [vmware/vsphere-automation-sdk-python#58]
- Steps or code snippet to reproduce

- Expected behavior

- Actual behavior

- Environment info

    - sdk package version: ```pip list | grep v```
    
    - python version:
    
    - vSphere version:

**Comment by tianhao64** [comment]
@rimsaoud Please refer to this KB article to manage vCenter services: https://kb.vmware.com/s/article/2109881

**Comment by rimsaoud** [comment]
hey,
Iknew this article but me i try to add him in python script like the
picture below  there is no API in
https://www.vmware.com/support/developer/vcsdk/visdk41pubs/ApiReference/vim.vm.Summary.html
and thanks for help
