### ISSUE TITLE
'vapi-client-bindings does not satisfy requirements'

### ISSUE THREAD

**Issue by gruden-g2** [vmware/vsphere-automation-sdk-python#77]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Environment
- sdk package version: 

- python version:

- vSphere version: 6.5

## Steps or code snippet to reproduce
pip install of current master sdk on Windows host with Python 3.6.5, no prior install of automation sdk.
## Actual behavior
Error: Could not find a version that satisfies the requirement vapi-client-bindings==1.3.1 (from -r requirements.txt (line5)) (from versions:2.5.0) matching distribution found for vapi-client-bindings==1.3.1 (from -r requirements.txt (line 5))
## Expected behavior
Install SDK

**Comment by tianhao64** [comment]
@gruden-g2 can you try below on windows?
pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file:\%CD%\lib

**Comment by arjun75x** [comment]
![capture](https://user-images.githubusercontent.com/29492173/41604680-6c41bd8c-73a5-11e8-95a0-c3461a4de80b.PNG)
It can't find the directories of anything under lib because the forward slashes become back slashes and it tries to find cached versions of the libs @tianhao64

**Comment by tianhao64** [comment]
@arjun75x Seems you are using power shell where %CD% doesn't give you current absolute path. Can you try it in cmd or pass the [absolute file path URL instead](https://en.wikipedia.org/wiki/File_URI_scheme#Windows)?

**Comment by tianhao64** [comment]
@arjun75x I am closing this for now. Please let me know if you still see issues.

**Comment by arjun75x** [comment]
@tianhao64 it didnt work on cmd or with the absolute path because it changes to the backslashes, but its fine Im using it on linux anyways now
