### ISSUE TITLE
What's the difference between vsphere-automation-sdk-python and pyvmomi

### ISSUE THREAD

**Issue by Prodesire** [vmware/vsphere-automation-sdk-python#79]
Well, as far as I know, both of them can do many same things like creating and running a vm.
I wonder what is the main difference between vsphere-automation-sdk-python and pyvmomi?
Thanks a lot.

**Comment by YagnaPhani** [comment]
I have same doubt too.. Can someone answer please?

**Comment by tianhao64** [comment]
PyVmomi used the vSphere web service APIs which are SOAP based APIs. For more info refer to: https://code.vmware.com/doc/preview?id=4206
vSphere Automation SDKs (python, java, .net, perl, ruby and REST) uses new version REST based APIs. Some new features like Tagging, Content Library, 
Appliance Management, NSX and VMware Cloud on AWS console APIs are only available through the Automation SDKs. Some existing SOAP based APIs, such as VM lifecycle and VC inventory APIs are also re-designed to support REST. For more info please see:  https://vmware.github.io/vsphere-automation-sdk/. Here is talk from @kmruddy about the new REST API: https://www.youtube.com/watch?v=nr3pJovtbzM

**Comment by linuxdan** [comment]
Will both libraries continue to be supported ?

**Comment by Prodesire** [comment]
@tianhao64 Thanks for explaining.

**Comment by tianhao64** [comment]
@linuxdan Yes, both will continue to be supported.
