### ISSUE TITLE
How to access instanceUuid

### ISSUE THREAD

**Issue by meetdash** [vmware/vsphere-automation-sdk-python#83]
- I am using the [latest SDK version]
- This API is compatible with my vCenter version
- I have searched [existing issues]

- sdk package version: 
pyvmomi                       6.7.0             
service-identity              17.0.0            
vapi-client-bindings          1.3.1             
vapi-common-client            2.9.0             
vapi-runtime                  2.9.0             
vapi-vmc-client               2.9.0             
vmc-app-python-sdk            2.2.0.0.0.15184434
vmc-client-bindings           1.2.0             

- python version:
Python 2.7.12

- vSphere version:
6.5.0

- Operating System/Shell (used to run SDK-based apps):
Ubuntu 16.04

**Comment by meetdash** [comment]
I need to get all members of all Grouping Objects in NSX-V, like VirtualMachines, IPSets, VirtualWire, etc.
And then I need to get their instanceUuids.
How can I do this using this API?

**Comment by tianhao64** [comment]
@meetdash Can you take a look at https://github.com/vmware/vsphere-automation-sdk-python/tree/master/samples/vmc/networks? Is this something you need?

**Comment by meetdash** [comment]
No, but I solved this issue using NSXCLI. Thanks
