### ISSUE TITLE
how to get vms in folder

### ISSUE THREAD

**Issue by navi86** [vmware/vsphere-automation-sdk-python#85]
I am trying to get VMs fro specific folder.
my code
from com.vmware.vcenter_client import VM
vm_svc = VM(stub_config)
vm_svc.list(VM.FilterSpec(folders=set(['vm'])))
In the result I got empty list.
What am I doing wrong ?
If don't use filter I get all VMs in venter.

**Comment by navi86** [comment]
Of course I have, it's the default folder in VMware group "VMs and Templates"

**Comment by tianhao64** [comment]
@navi86 Just realized what's the problem. The folders parameter in VM.FilterSpec takes IDs instead of names. You have to get the folder ID first. The below code snippet should work for you:

```
import ssl
import requests
from vmware.vapi.vsphere.client import create_vsphere_client
from com.vmware.vcenter_client import VM, Folder

session = requests.session()
session.verify = False
client = create_vsphere_client(server='xxxxx',
                               username='xxxxxx', 
                               password='xxxxxx', 
                               session=session)

folder_filter = Folder.FilterSpec(names=set(['vm']))
folder_id = client.vcenter.Folder.list(folder_filter)[0].folder
vm_filter = VM.FilterSpec(folders=set([folder_id]))
client.vcenter.VM.list(vm_filter)
```

**Comment by navi86** [comment]
open
But it doesn't get vms in subfolders.
