### ISSUE TITLE
how to get vms in folder 

### ISSUE THREAD

**Issue by navi86** [vmware/vsphere-automation-sdk-python#87]
I am trying to get VMs from specific folder and subfolders.
I've opened issue 85, but the solution doesn't provide with vms in subfolder.
Is it not possible to get vms in subfolders ?

**Comment by tianhao64** [comment]
The API currently doesn't include vms in subfolders. I just checked the API doc and it doesn't mention this behavior. I will file a bug to fix the doc. I will also file a feature request to add the recursive capability to the API.

**Comment by mike-19** [comment]
any idea on when this feature will be made available?

**Comment by vazome** [comment]
It seems like you can already do it with `client.vcenter.VM.list(VM.FilterSpec(folders=folder_id))`
https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/data-structures/VM/FilterSpec/
