### ISSUE TITLE
ModuleNotFoundError: No module named 'vmware.vapi.vsphere'

### ISSUE THREAD

**Issue by WalterWo** [vmware/vsphere-automation-sdk-python#91]
- [X] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [ ] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [X] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Environment
- sdk package version: 

`master`
- python version:

`python 3.6.3`
- vSphere version:

- Operating System/Shell (used to run SDK-based apps):
`Centos 7.5`
## Actual behavior
`pip3 install --upgrade --force-reinstall -r requirements.txt --extra-index-url file://$PWD/lib` install successfully` :
```
Successfully installed Automat-0.7.0 PyHamcrest-1.9.0 asn1crypto-0.24.0 attrs-18.1.0 certifi-2018.8.24 cffi-1.11.5 chardet-3.0.4 constantly-15.1.0 cryptography-2.3.1 hyperlink-18.0.0 idna-2.7 incremental-17.5.0 lxml-4.2.4 nsx-policy-python-sdk-2.2.0.0.0.15184434 pyOpenSSL-18.0.0 pyVmomi-6.7.0 pyasn1-0.4.4 pyasn1-modules-0.2.2 pycparser-2.18 requests-2.19.1 service-identity-17.0.0 setuptools-40.2.0 simplejson-3.16.0 six-1.11.0 suds-jurko-0.6 tabulate-0.8.2 twisted-18.7.0 urllib3-1.23 vapi-client-bindings-2.5.0 vapi-common-client-2.9.0 vapi-runtime-2.9.0 vapi-vmc-client-2.9.0 vmc-app-python-sdk-2.2.0.0.0.15184434 vmc-client-bindings-1.2.0 werkzeug-0.14.1 zope.interface-4.5.0
```
Test as guide sample but get below error :
```
>>> import requests
>>> import urllib3
>>> from vmware.vapi.vsphere.client import create_vsphere_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'vmware.vapi.vsphere'
```

**Comment by tianhao64** [comment]
@WalterWo Seems vapi-client-binding didn't re-installed correctly. The right version should be 1.3.1. 
Can you post the output of the pip install cmd?

**Comment by khalilnawar** [comment]
same issue here with the vapi-client-bindings version 1.3.1
$ pip freeze | grep vapi
vapi-client-bindings==1.3.1
vapi-common-client==2.9.0
vapi-runtime==2.9.0
vapi-vmc-client==2.9.0

**Comment by tianhao64** [comment]
@khalilnawar do you still have the same issue? Can you post the complete output of the pip install cmd?

**Comment by tianhao64** [comment]
@WalterWo @khalilnawar I am closing this due to missing info. Feel free to reopen with needed info if you still see issues.

**Comment by vladinux86** [comment]
wget https://bootstrap.pypa.io/get-pip.py
python3.6 get-pip.py
python3.6 -m pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file:///<PATH>

**Comment by cormite** [comment]
If you run into a problem like this:

<pre>Cannot uninstall 'certifi'.
It is a distutils installed project and thus we cannot accurately determine
which files belong to it which would lead to only a partial uninstall.</pre>
It happened to me when running the pip install command with an active conda 3.6.8 environment. You could all --ignore-installed like so to solve it:

<pre>
$ git clone https://github.com/vmware/vsphere-automation-sdk-python.git
$ cd vsphere-automation-sdk-python
$ pip install --upgrade --force-reinstall --ignore-installed -r requirements.txt \
--extra-index-url file:///$PWD/lib
</pre>

**Comment by Rajeev244** [comment]
@tianhao64  sir i have already installed all the packages mentioned in the requirement.txt file but still i am getting the error "Module not found".Here is the complete

**Comment by anusha94** [comment]
@Rajeev244 
have you set the PYTHONPATH as mentioned here? - [set PYTHONPATH](https://github.com/vmware/vsphere-automation-sdk-python#first-set-pythonpath-to-use-sdk-helper-methods)

**Comment by Rajeev244** [comment]
@anusha94 .Thanks for your response ,the issue got resolved .

**Comment by rahulyadav130** [comment]
@Rajeev244 how this issue got resolved?

**Comment by Rajeev244** [comment]
@rahulyadav130 .Kindly set the path variable correctly and ten clone the repository.It should work.frankly speaking i did long back.Let me know if you still faces issue.

**Comment by kyok0** [comment]
in case someone still has this issue - make sure your file is not called vmware.py , as it will conflict with the package name, causing the ModuleNotFoundError. 
A silly mistake, but often overlooked, as it was in my case..
