### ISSUE TITLE
com.vmware.vapi.std.errors_client.OperationNotFound

### ISSUE THREAD

**Issue by shenmingxing** [vmware/vsphere-automation-sdk-python#93]
code:
import requests
import urllib3

from vmware.vapi.vsphere.client import create_vsphere_client
session = requests.session()
 
# Disable cert verification for demo purpose. 
# This is not recommended in a production environment.
session.verify = False
 
# Disable the secure connection warning for demo purpose.
# This is not recommended in a production environment.
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
 
# Connect to a vCenter Server using username and password
vsphere_client = create_vsphere_client(server='192.168.8.85', username='administrator@vc.dev', password='1qaz@WSX', session=session) 
# List all VMs inside the vCenter Server
print(vsphere_client.vcenter.VM.list())

but error under

Traceback (most recent call last):
  File "ml_vmuuid.py", line 29, in <module>
    print(vsphere_client.vcenter.Datacenter.list(None))
  File "C:\Users\15470\AppData\Roaming\Python\Python36\site-packages\com\vmware\vcenter_client.py", line 619, in list
    'filter': filter,
  File "C:\Users\15470\AppData\Roaming\Python\Python36\site-packages\vmware\vapi\bindings\stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "C:\Users\15470\AppData\Roaming\Python\Python36\site-packages\vmware\vapi\bindings\stub.py", line 275, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.OperationNotFound: {messages : [LocalizableMessage(id='vapi.method.input.invalid.interface', default_message='æ\x89¾ä¸\x8då\x88°æ\x9c\x8då\x8a¡â\x80\x9ccom.vmware.vcenter.datacenterâ\x80\x9dã\x80\x82', args=['com.vmware.vcenter.datacenter'])], data : None}

G:\eclipse_work\python-test-one\src\com\ml>

**Comment by tianhao64** [comment]
Looks like the datacenter name is using non-ascii chars? I will try to reproduce this issue.

**Comment by tianhao64** [comment]
@shenmingxing Sorry to get back to you late. Seems the issue is not related to the datacenter name. What's your vcenter version? The listing vm API was introduced since vSphere 6.5.

**Comment by tianhao64** [comment]
It's very likely that the vcenter doesn't support VM APIs. Please double check. Let me know if it's not the case.
