### ISSUE TITLE
com.vmware.vapi.std.errors_client.OperationNotFound

### ISSUE THREAD

**Issue by khalilnawar** [vmware/vsphere-automation-sdk-python#98]
Hi,

I went to create virtual machine in VMWARE VCENTER with  python script. I tested scripts in this link : https://github.com/vmware/vsphere-automation-sdk-python/tree/master/samples/vsphere/vcenter/vm     i tested create create_exhaustive_vm  and delete_vm , error appear with create  : com.vmware.vapi.std.errors_client.OperationNotFound: {data : None, messages : [LocalizableMessage(default_message="Cannot find service 'com.vmware.vcenter.VM'.", args=['com.vmware.vcenter.VM'], id='vapi.method.input.invalid.interface')]}
 
Error in delete vm : com.vmware.vapi.std.errors_client.OperationNotFound: {data : None, messages : [LocalizableMessage(default_message="Cannot find service 'com.vmware.vcenter.VM'.", args=['com.vmware.vcenter.VM'], id='vapi.method.input.invalid.interface')]} 
 
Same error  , please how to resolve this problem.

**Comment by khalilnawar** [comment]
@alanrenouf

**Comment by tianhao64** [comment]
@khalilnawar What's your VC version?

**Comment by khalilnawar** [comment]
Vcenter Server 6.0 U2

**Comment by tianhao64** [comment]
The vm APIs are introduced since 6.5 as indicated in each sample: https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/vcenter/vm/delete_vm.py#L17. 
vCenter 6.0 supports content library and tagging APIs.

**Comment by khalilnawar** [comment]
@tianhao64  and ESXI version ?

**Comment by alanrenouf** [comment]
This API is not currently on ESXi, if you wish to create a VM on ESX/VC in 6.0 U2 you will need to use one of the pyvmomi samples for now https://github.com/vmware/pyvmomi-community-samples/tree/master/samples which uses the soap api.
